In [ ]:
# Install dependencies first:
#!pip install codecarbon
!pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [ ]:
'G:\\Mon Drive\\TP2_Green_IT\\Data\\archive.zip'
from google.colab import drive
drive.mount('/gdrive')
!ls '/gdrive'
fichier_archive = 'gdrive/MyDrive/TP2_Green_IT/Data/archive.zip'

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
MyDrive

In [ ]:
#@title
!unzip '/gdrive/MyDrive/TP2_Green_IT/Data/archive.zip'

Archive:  /gdrive/MyDrive/TP2_Green_IT/Data/archive.zip
replace Books_rating.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [ ]:
#import codecarbon
#from codecarbon import EmissionsTracker
import numpy as np
import os
import pandas as pd

In [ ]:
#Read books_rating
books_rating_df = pd.read_csv('Books_rating.csv')
print("Contents of Books_rating.csv:")
display(books_rating_df.head())

#Read books_data
books_data_df = pd.read_csv('books_data.csv')
print("Contents of Books_data.csv:")
display(books_data_df.head())

Contents of Books_rating.csv:

,Id,Title,Price,User_id,profileName,review/helpfulness,review/score,review/time,review/summary,review/text
0,1882931173,Its Only Art If Its Well Hung!,NaN,AVCGYZL8FQQTD,"Jim of Oz ""jim-of-oz""",7/7,4.0,940636800,Nice collection of Julie Strain images,This is only for Julie Strain fans. It's a col...
1,0826414346,Dr. Seuss: American Icon,NaN,A30TK6U7DNS82R,Kevin Killian,10/10,5.0,1095724800,Really Enjoyed It,I don't care much for Dr. Seuss but after read...
2,0826414346,Dr. Seuss: American Icon,NaN,A3UH4UZ4RSVO82,John Granger,10/11,5.0,1078790400,Essential for every personal and Public Library,"If people become the books they read and if ""t..."
3,0826414346,Dr. Seuss: American Icon,NaN,A2MVUWT453QH61,"Roy E. Perry ""amateur philosopher""",7/7,4.0,1090713600,Phlip Nel gives silly Seuss a serious treatment,"Theodore Seuss Geisel (1904-1991), aka &quot;D..."
4,0826414346,Dr. Seuss: American Icon,NaN,A22X4XUPKF66MR,"D. H. Richards ""ninthwavestore""",3/3,4.0,1107993600,Good academic overview,Philip Nel - Dr. Seuss: American IconThis is b...

Contents of Books_data.csv:

,Title,description,authors,image,previewLink,publisher,publishedDate,infoLink,categories,ratingsCount
0,Its Only Art If Its Well Hung!,NaN,['Julie Strain'],http://books.google.com/books/content?id=DykPA...,http://books.google.nl/books?id=DykPAAAACAAJ&d...,NaN,1996,http://books.google.nl/books?id=DykPAAAACAAJ&d...,['Comics & Graphic Novels'],NaN
1,Dr. Seuss: American Icon,Philip Nel takes a fascinating look into the k...,['Philip Nel'],http://books.google.com/books/content?id=IjvHQ...,http://books.google.nl/books?id=IjvHQsCn_pgC&p...,A&C Black,2005-01-01,http://books.google.nl/books?id=IjvHQsCn_pgC&d...,['Biography & Autobiography'],NaN
2,Wonderful Worship in Smaller Churches,This resource includes twelve principles in un...,['David R. Ray'],http://books.google.com/books/content?id=2tsDA...,http://books.google.nl/books?id=2tsDAAAACAAJ&d...,NaN,2000,http://books.google.nl/books?id=2tsDAAAACAAJ&d...,['Religion'],NaN
3,Whispers of the Wicked Saints,Julia Thomas finds her life spinning out of co...,['Veronica Haddon'],http://books.google.com/books/content?id=aRSIg...,http://books.google.nl/books?id=aRSIgJlq6JwC&d...,iUniverse,2005-02,http://books.google.nl/books?id=aRSIgJlq6JwC&d...,['Fiction'],NaN
4,"Nation Dance: Religion, Identity and Cultural ...",NaN,['Edward Long'],NaN,http://books.google.nl/books?id=399SPgAACAAJ&d...,NaN,2003-03-01,http://books.google.nl/books?id=399SPgAACAAJ&d...,NaN,NaN

In [ ]:
print("Checking for missing values in books_rating_df:")
display(books_rating_df.isnull().sum())

print("\nChecking for missing values in books_data_df:")
display(books_data_df.isnull().sum())

Checking for missing values in books_rating_df:

[codecarbon INFO @ 11:11:02] Energy consumed for RAM : 0.000843 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:11:02] Delta energy consumed for CPU with constant : 0.000064 kWh, power : 120.0 W
[codecarbon INFO @ 11:11:02] Energy consumed for All CPU : 0.010258 kWh
[codecarbon INFO @ 11:11:02] 0.011101 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:11:02] Energy consumed for RAM : 0.000493 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:11:02] Energy consumed for RAM : 0.000763 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:11:02] Energy consumed for RAM : 0.000506 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:11:02] 0.019656 g.CO2eq/s mean an estimation of 619.8645331725579 kg.CO2eq/year
[codecarbon INFO @ 11:11:02] Delta energy consumed for CPU with constant : 0.000046 kWh, power : 120.0 W
[codecarbon INFO @ 11:11:02] Energy consumed for All CPU : 0.006017 kWh
[codecarbon INFO @ 11:11:02] Delta energy consumed for CPU with constant : 0.000046 kWh, power : 120.0 W
[codecarbon INFO @ 11:11:02] Energy consumed for All CPU : 0.006153 kWh
[codecarbon INFO @ 11:11:02] 0.006510 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:11:02] Delta energy consumed for CPU with constant : 0.000045 kWh, power : 120.0 W

Id                          0
Title                     208
Price                 2518829
User_id                561787
profileName            561905
review/helpfulness          0
review/score                0
review/time                 0
review/summary            407
review/text                 8
dtype: int64

[codecarbon INFO @ 11:11:02] 0.006659 kWh of electricity and 0.000000 L of water were used since the beginning.

Checking for missing values in books_data_df:

Title                 1
description       68442
authors           31413
image             52075
previewLink       23836
publisher         75886
publishedDate     25305
infoLink          23836
categories        41199
ratingsCount     162652
dtype: int64

[codecarbon INFO @ 11:11:02] Energy consumed for All CPU : 0.009290 kWh
[codecarbon INFO @ 11:11:02] 0.010052 kWh of electricity and 0.000000 L of water were used since the beginning.

In [ ]:
# Select the specified columns from books_rating_df
sbooks_rating_df = books_rating_df[['Title', 'review/score', 'review/text']]
sbooks_rating_df = sbooks_rating_df.copy()

# Drop rows where 'Title', 'review/summary', or 'review/text' are missing
# Fill missing 'ratingsCount' with 0
sbooks_rating_df.fillna({
    'review/score': 0,
    'Title': 'Unknown',
    'review/text': 'Unknown'
    }, inplace=True)

display(sbooks_rating_df.isnull().sum())

Title           0
review/score    0
review/text     0
dtype: int64

In [ ]:
# Display the first few rows of the new DataFrame
#print("Selected columns from books_rating_df:")
#display(sbooks_rating_df.head())
sbooks_data_df = books_data_df[['Title', 'authors', 'publisher', 'categories','ratingsCount']]
sbooks_data_df = sbooks_data_df.copy()
sbooks_data_df.fillna({
    'ratingsCount': 0,
    'Title': 'Unknown',
    'authors': 'Unknown',
    'publisher': 'Unknown',
    'categories': 'Unknown'
}, inplace=True)

display(sbooks_data_df.isnull().sum())

# Display the first few rows of the new DataFrame
#print("Selected columns from books_data_df:")
#display(sbooks_data_df.head())

Title           0
authors         0
publisher       0
categories      0
ratingsCount    0
dtype: int64

In [ ]:
display(sbooks_data_df[['Title', 'authors', 'categories']].head())

,Title,authors,categories
0,Its Only Art If Its Well Hung!,['Julie Strain'],['Comics & Graphic Novels']
1,Dr. Seuss: American Icon,['Philip Nel'],['Biography & Autobiography']
2,Wonderful Worship in Smaller Churches,['David R. Ray'],['Religion']
3,Whispers of the Wicked Saints,['Veronica Haddon'],['Fiction']
4,"Nation Dance: Religion, Identity and Cultural ...",['Edward Long'],Unknown

In [ ]:
import ast

# Function to safely convert string representation of list to a list
def safe_literal_eval(x):
    try:
        return ast.literal_eval(x)
    except (ValueError, SyntaxError):
        return []

# Apply the function to 'authors' and 'categories' columns in sbooks_data_df
sbooks_data_df['authors'] = sbooks_data_df['authors'].apply(safe_literal_eval)
sbooks_data_df['categories'] = sbooks_data_df['categories'].apply(safe_literal_eval)

print("Normalized 'authors' and 'categories' columns in sbooks_data_df:")
display(sbooks_data_df[['Title', 'authors', 'categories']].head())

Normalized 'authors' and 'categories' columns in sbooks_data_df:

,Title,authors,categories
0,Its Only Art If Its Well Hung!,[Julie Strain],[Comics & Graphic Novels]
1,Dr. Seuss: American Icon,[Philip Nel],[Biography & Autobiography]
2,Wonderful Worship in Smaller Churches,[David R. Ray],[Religion]
3,Whispers of the Wicked Saints,[Veronica Haddon],[Fiction]
4,"Nation Dance: Religion, Identity and Cultural ...",[Edward Long],[]

In [ ]:
# Voir les 10 premières valeurs brutes
print(sbooks_data_df['authors'].head(10))
print(sbooks_data_df['categories'].head(10))

# Voir le type des valeurs
print(sbooks_data_df['authors'].apply(type).value_counts())

0            [Julie Strain]
1              [Philip Nel]
2            [David R. Ray]
3         [Veronica Haddon]
4             [Edward Long]
5        [Everett Ferguson]
6    [Miriam Allen De Ford]
7            [Lee Blessing]
8    [Mary Fabyan Windeatt]
9          [Steven Wardell]
Name: authors, dtype: object
0      [Comics & Graphic Novels]
1    [Biography & Autobiography]
2                     [Religion]
3                      [Fiction]
4                             []
5                     [Religion]
6                             []
7                             []
8    [Biography & Autobiography]
9               [Social Science]
Name: categories, dtype: object
authors
<class 'list'>    212404
Name: count, dtype: int64

In [ ]:
!pip install codecarbon

Requirement already satisfied: codecarbon in /usr/local/lib/python3.12/dist-packages (3.0.8)
Requirement already satisfied: arrow in /usr/local/lib/python3.12/dist-packages (from codecarbon) (1.4.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from codecarbon) (8.3.0)
Requirement already satisfied: fief-client[cli] in /usr/local/lib/python3.12/dist-packages (from codecarbon) (0.20.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from codecarbon) (2.2.2)
Requirement already satisfied: prometheus_client in /usr/local/lib/python3.12/dist-packages (from codecarbon) (0.23.1)
Requirement already satisfied: psutil>=6.0.0 in /usr/local/lib/python3.12/dist-packages (from codecarbon) (7.1.2)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.12/dist-packages (from codecarbon) (9.0.0)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from codecarbon) (2.11.10)
Requirement already satisfied: nvidia-ml-py in /usr/local/lib/python3.12/dist-packages (from codecarbon) (12.575.51)
Requirement already satisfied: rapidfuzz in /usr/local/lib/python3.12/dist-packages (from codecarbon) (3.14.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from codecarbon) (2.32.4)
Requirement already satisfied: questionary in /usr/local/lib/python3.12/dist-packages (from codecarbon) (2.1.1)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from codecarbon) (13.9.4)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from codecarbon) (0.20.0)
Requirement already satisfied: python-dateutil>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from arrow->codecarbon) (2.9.0.post0)
Requirement already satisfied: tzdata in /usr/local/lib/python3.12/dist-packages (from arrow->codecarbon) (2025.2)
Requirement already satisfied: httpx<0.28.0,>=0.21.3 in /usr/local/lib/python3.12/dist-packages (from fief-client[cli]->codecarbon) (0.27.2)
Requirement already satisfied: jwcrypto<2.0.0,>=1.4 in /usr/local/lib/python3.12/dist-packages (from fief-client[cli]->codecarbon) (1.5.6)
Requirement already satisfied: yaspin in /usr/local/lib/python3.12/dist-packages (from fief-client[cli]->codecarbon) (3.3.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->codecarbon) (2.0.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->codecarbon) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->codecarbon) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic->codecarbon) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.12/dist-packages (from pydantic->codecarbon) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->codecarbon) (0.4.2)
Requirement already satisfied: prompt_toolkit<4.0,>=2.0 in /usr/local/lib/python3.12/dist-packages (from questionary->codecarbon) (3.0.52)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->codecarbon) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->codecarbon) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->codecarbon) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->codecarbon) (2025.10.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->codecarbon) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->codecarbon) (2.19.2)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->codecarbon) (1.5.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<0.28.0,>=0.21.3->fief-client[cli]->codecarbon) (4.11.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<0.28.0,>=0.21.3->fief-client[cli]->codecarbon) (1.0.9)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from httpx<0.28.0,>=0.21.3->fief-client[cli]->codecarbon) (1.3.1)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<0.28.0,>=0.21.3->fief-client[cli]->codecarbon) (0.16.0)
Requirement already satisfied: cryptography>=3.4 in /usr/local/lib/python3.12/dist-packages (from jwcrypto<2.0.0,>=1.4->fief-client[cli]->codecarbon) (43.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->codecarbon) (0.1.2)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt_toolkit<4.0,>=2.0->questionary->codecarbon) (0.2.14)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7.0->arrow->codecarbon) (1.17.0)
Requirement already satisfied: termcolor<4.0,>=3.1 in /usr/local/lib/python3.12/dist-packages (from yaspin->fief-client[cli]->codecarbon) (3.2.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=3.4->jwcrypto<2.0.0,>=1.4->fief-client[cli]->codecarbon) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=3.4->jwcrypto<2.0.0,>=1.4->fief-client[cli]->codecarbon) (2.23)

In [ ]:
import codecarbon
from codecarbon import EmissionsTracker
import numpy as np
import os
import pandas as pd

# Optional: define an output directory for logs
log_dir = "/gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3"
os.makedirs(log_dir, exist_ok=True)

In [ ]:

# Initialize the tracker with detailed logging
tracker = EmissionsTracker(
    project_name="demo_experiment",
    output_dir=log_dir,
    measure_power_secs=1,        # frequency of power measurement
    log_level="info",            # ensures detailed console + file logs
    save_to_file=True,           # ensure CSV file is written
)

# Start tracking
tracker.start()

# Simulate a computation workload
for _ in range(1000):
    a = np.random.rand(500, 500)
    b = np.random.rand(500, 500)
    np.dot(a, b)

book_df = pd.merge(
    sbooks_data_df,
    sbooks_rating_df,
    on='Title',
    how='inner'  # options: 'inner', 'left', 'right', 'outer'
)

#print(book_df.header())
#print("\nShape:", book_df.shape)
#display(book_df)
print(book_df.columns)


# Stop tracking
emissions = tracker.stop()

# Print summary
print("\n=== CodeCarbon Tracking Summary ===")
print(f"Project: {tracker._project_name}")
print(f"Output CSV: {os.path.join(log_dir, 'emissions_pandas.csv')}")

[codecarbon WARNING @ 12:45:27] Multiple instances of codecarbon are allowed to run at the same time.
[codecarbon INFO @ 12:45:27] [setup] RAM Tracking...
[codecarbon INFO @ 12:45:27] [setup] CPU Tracking...
[codecarbon WARNING @ 12:45:29] No CPU tracking mode found. Falling back on estimation based on TDP for CPU.
 Linux OS detected: Please ensure RAPL files exist at /sys/class/powercap/intel-rapl/subsystem to measure CPU

[codecarbon INFO @ 12:45:29] CPU Model on constant consumption mode: AMD EPYC 7B12
[codecarbon WARNING @ 12:45:29] No CPU tracking mode found. Falling back on CPU constant mode.
[codecarbon INFO @ 12:45:29] [setup] GPU Tracking...
[codecarbon INFO @ 12:45:29] No GPU found.
[codecarbon INFO @ 12:45:29] The below tracking methods have been set up:
                RAM Tracking Method: RAM power estimation model
                CPU Tracking Method: global constant
                GPU Tracking Method: Unspecified

[codecarbon INFO @ 12:45:29] >>> Tracker's metadata:
[codecarbon INFO @ 12:45:29]   Platform system: Linux-6.6.105+-x86_64-with-glibc2.35
[codecarbon INFO @ 12:45:29]   Python version: 3.12.12
[codecarbon INFO @ 12:45:29]   CodeCarbon version: 3.0.8
[codecarbon INFO @ 12:45:29]   Available RAM : 12.671 GB
[codecarbon INFO @ 12:45:29]   CPU count: 2 thread(s) in 1 physical CPU(s)
[codecarbon INFO @ 12:45:29]   CPU model: AMD EPYC 7B12
[codecarbon INFO @ 12:45:29]   GPU count: None
[codecarbon INFO @ 12:45:29]   GPU model: None
[codecarbon INFO @ 12:45:29] Emissions data (if any) will be saved to file /gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emissions.csv
[codecarbon INFO @ 12:45:30] Energy consumed for RAM : 0.000003 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:45:30] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 12:45:30] Energy consumed for All CPU : 0.000034 kWh
[codecarbon INFO @ 12:45:30] 0.000036 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:45:31] Energy consumed for RAM : 0.000006 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:45:31] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:45:31] Energy consumed for All CPU : 0.000067 kWh
[codecarbon INFO @ 12:45:31] 0.000072 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:45:32] Energy consumed for RAM : 0.000008 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:45:32] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:45:32] Energy consumed for All CPU : 0.000100 kWh
[codecarbon INFO @ 12:45:32] 0.000108 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:45:33] Energy consumed for RAM : 0.000011 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:45:33] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:45:33] Energy consumed for All CPU : 0.000133 kWh
[codecarbon INFO @ 12:45:33] 0.000144 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:45:34] Energy consumed for RAM : 0.000014 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:45:34] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:45:34] Energy consumed for All CPU : 0.000167 kWh
[codecarbon INFO @ 12:45:34] 0.000180 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:45:35] Energy consumed for RAM : 0.000017 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:45:35] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:45:35] Energy consumed for All CPU : 0.000200 kWh
[codecarbon INFO @ 12:45:35] 0.000216 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:45:36] Energy consumed for RAM : 0.000019 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:45:36] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:45:36] Energy consumed for All CPU : 0.000233 kWh
[codecarbon INFO @ 12:45:36] 0.000252 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:45:37] Energy consumed for RAM : 0.000022 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:45:37] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:45:37] Energy consumed for All CPU : 0.000266 kWh
[codecarbon INFO @ 12:45:37] 0.000288 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:45:37] 0.016239 g.CO2eq/s mean an estimation of 512.1066945440215 kg.CO2eq/year
[codecarbon INFO @ 12:45:38] Energy consumed for RAM : 0.000025 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:45:38] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:45:38] Energy consumed for All CPU : 0.000299 kWh
[codecarbon INFO @ 12:45:38] 0.000324 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:45:39] Energy consumed for RAM : 0.000028 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:45:39] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:45:39] Energy consumed for All CPU : 0.000332 kWh
[codecarbon INFO @ 12:45:39] 0.000360 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:45:40] Energy consumed for RAM : 0.000030 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:45:40] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:45:40] Energy consumed for All CPU : 0.000365 kWh
[codecarbon INFO @ 12:45:40] 0.000395 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:45:41] Energy consumed for RAM : 0.000033 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:45:41] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:45:41] Energy consumed for All CPU : 0.000398 kWh
[codecarbon INFO @ 12:45:41] 0.000431 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:45:42] Energy consumed for RAM : 0.000037 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:45:42] Delta energy consumed for CPU with constant : 0.000042 kWh, power : 120.0 W
[codecarbon INFO @ 12:45:42] Energy consumed for All CPU : 0.000440 kWh
[codecarbon INFO @ 12:45:42] 0.000477 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:45:43] Energy consumed for RAM : 0.000039 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:45:43] Delta energy consumed for CPU with constant : 0.000036 kWh, power : 120.0 W
[codecarbon INFO @ 12:45:44] Energy consumed for All CPU : 0.000476 kWh
[codecarbon INFO @ 12:45:44] 0.000515 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:45:44] Energy consumed for RAM : 0.000041 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:45:44] Delta energy consumed for CPU with constant : 0.000017 kWh, power : 120.0 W
[codecarbon INFO @ 12:45:44] Energy consumed for All CPU : 0.000493 kWh
[codecarbon INFO @ 12:45:44] 0.000533 kWh of electricity and 0.000000 L of water were used since the beginning.

Index(['Title', 'authors', 'publisher', 'categories', 'ratingsCount',
       'review/score', 'review/text'],
      dtype='object')

=== CodeCarbon Tracking Summary ===
Project: demo_experiment
Output CSV: /gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emissions_pandas.csv

In [ ]:

# Initialize the tracker with detailed logging
tracker = EmissionsTracker(
    project_name="demo_experiment",
    output_dir=log_dir,
    measure_power_secs=1,        # frequency of power measurement
    log_level="info",            # ensures detailed console + file logs
    save_to_file=True,           # ensure CSV file is written
)

# Start tracking
tracker.start()

# Simulate a computation workload
for _ in range(1000):
    a = np.random.rand(500, 500)
    b = np.random.rand(500, 500)
    np.dot(a, b)

book_df = pd.merge(
    sbooks_data_df,
    sbooks_rating_df,
    on='Title',
    how='inner'  # options: 'inner', 'left', 'right', 'outer'
)

#print(book_df.header())
#print("\nShape:", book_df.shape)
#display(book_df)
print(book_df.columns)

# Stop tracking
emissions = tracker.stop()

# Print summary
print("\n=== CodeCarbon Tracking Summary ===")
print(f"Project: {tracker._project_name}")
print(f"Output CSV: {os.path.join(log_dir, 'emissions_pandas.csv')}")

[codecarbon INFO @ 11:17:57] Energy consumed for RAM : 0.000058 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:17:57] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:17:57] Energy consumed for All CPU : 0.000695 kWh
[codecarbon INFO @ 11:17:57] 0.000753 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:17:57] Energy consumed for RAM : 0.000162 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:17:57] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:17:57] Energy consumed for All CPU : 0.001958 kWh
[codecarbon INFO @ 11:17:57] 0.002121 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:17:57] Energy consumed for RAM : 0.000887 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:17:57] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:17:57] Energy consumed for All CPU : 0.010672 kWh
[codecarbon INFO @ 11:17:57] 0.011560 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:17:57] Energy consumed for RAM : 0.001646 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:17:57] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:17:57] Energy consumed for All CPU : 0.019988 kWh
[codecarbon INFO @ 11:17:57] 0.021634 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:17:58] Energy consumed for RAM : 0.001635 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:17:58] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:17:58] Energy consumed for All CPU : 0.019740 kWh
[codecarbon INFO @ 11:17:58] Energy consumed for RAM : 0.001985 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:17:58] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:17:58] 0.021375 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:17:58] Energy consumed for All CPU : 0.023987 kWh
[codecarbon INFO @ 11:17:58] 0.025972 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:17:58] Energy consumed for RAM : 0.001906 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:17:58] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:17:58] Energy consumed for All CPU : 0.023095 kWh
[codecarbon INFO @ 11:17:58] 0.025001 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:17:58] 0.016161 g.CO2eq/s mean an estimation of 509.6598731784871 kg.CO2eq/year
[codecarbon INFO @ 11:17:58] Energy consumed for RAM : 0.000060 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:17:58] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:17:58] Energy consumed for All CPU : 0.000729 kWh
[codecarbon INFO @ 11:17:58] 0.000789 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:17:58] Energy consumed for RAM : 0.000165 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:17:58] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:17:58] Energy consumed for All CPU : 0.001991 kWh
[codecarbon INFO @ 11:17:58] 0.002157 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:17:58] Energy consumed for RAM : 0.000890 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:17:58] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:17:58] Energy consumed for All CPU : 0.010706 kWh
[codecarbon INFO @ 11:17:58] 0.011596 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:17:58] Energy consumed for RAM : 0.001649 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:17:58] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:17:58] Energy consumed for All CPU : 0.020021 kWh
[codecarbon INFO @ 11:17:58] 0.021670 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:17:59] Energy consumed for RAM : 0.001638 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:17:59] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:17:59] Energy consumed for All CPU : 0.019772 kWh
[codecarbon INFO @ 11:17:59] 0.021410 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:17:59] Energy consumed for RAM : 0.001988 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:17:59] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:17:59] Energy consumed for All CPU : 0.024020 kWh
[codecarbon INFO @ 11:17:59] 0.026008 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:17:59] 0.016138 g.CO2eq/s mean an estimation of 508.9295125081204 kg.CO2eq/year
[codecarbon INFO @ 11:17:59] Energy consumed for RAM : 0.001909 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:17:59] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:17:59] Energy consumed for All CPU : 0.023128 kWh
[codecarbon INFO @ 11:17:59] 0.025037 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:17:59] Energy consumed for RAM : 0.000063 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:17:59] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 11:17:59] Energy consumed for All CPU : 0.000762 kWh
[codecarbon INFO @ 11:17:59] 0.000825 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:17:59] Energy consumed for RAM : 0.000168 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:17:59] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:17:59] Energy consumed for All CPU : 0.002025 kWh
[codecarbon INFO @ 11:17:59] 0.002193 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:17:59] Energy consumed for RAM : 0.000893 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:17:59] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:17:59] Energy consumed for All CPU : 0.010739 kWh
[codecarbon INFO @ 11:17:59] 0.011632 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:17:59] Energy consumed for RAM : 0.001652 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:17:59] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:17:59] Energy consumed for All CPU : 0.020054 kWh
[codecarbon INFO @ 11:17:59] 0.021706 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:00] Energy consumed for RAM : 0.001641 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:00] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:00] Energy consumed for All CPU : 0.019805 kWh
[codecarbon INFO @ 11:18:00] 0.021446 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:00] 0.016130 g.CO2eq/s mean an estimation of 508.6894601084726 kg.CO2eq/year
[codecarbon INFO @ 11:18:00] Energy consumed for RAM : 0.001991 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:00] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:00] Energy consumed for All CPU : 0.024053 kWh
[codecarbon INFO @ 11:18:00] 0.026044 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:00] Energy consumed for RAM : 0.001912 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:00] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:00] Energy consumed for All CPU : 0.023162 kWh
[codecarbon INFO @ 11:18:00] 0.025073 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:00] Energy consumed for RAM : 0.000066 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:00] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:00] Energy consumed for All CPU : 0.000795 kWh
[codecarbon INFO @ 11:18:00] 0.000861 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:00] 0.016203 g.CO2eq/s mean an estimation of 510.9918439356093 kg.CO2eq/year
[codecarbon INFO @ 11:18:00] Energy consumed for RAM : 0.000171 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:00] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:00] Energy consumed for All CPU : 0.002058 kWh
[codecarbon INFO @ 11:18:00] 0.002228 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:00] Energy consumed for RAM : 0.000896 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:00] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:00] Energy consumed for All CPU : 0.010772 kWh
[codecarbon INFO @ 11:18:00] 0.011667 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:00] Energy consumed for RAM : 0.001655 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:00] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:00] Energy consumed for All CPU : 0.020087 kWh
[codecarbon INFO @ 11:18:00] 0.021742 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:01] Energy consumed for RAM : 0.001644 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:01] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:01] Energy consumed for All CPU : 0.019838 kWh
[codecarbon INFO @ 11:18:01] 0.021482 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:01] Energy consumed for RAM : 0.001994 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:01] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:01] Energy consumed for All CPU : 0.024086 kWh
[codecarbon INFO @ 11:18:01] 0.026080 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:01] Energy consumed for RAM : 0.001914 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:01] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:01] Energy consumed for All CPU : 0.023195 kWh
[codecarbon INFO @ 11:18:01] 0.025109 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:01] Energy consumed for RAM : 0.000069 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:01] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:01] Energy consumed for All CPU : 0.000828 kWh
[codecarbon INFO @ 11:18:01] 0.000897 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:01] Energy consumed for RAM : 0.000173 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:01] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:01] Energy consumed for All CPU : 0.002091 kWh
[codecarbon INFO @ 11:18:01] 0.002264 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:01] Energy consumed for RAM : 0.000898 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:01] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:01] Energy consumed for All CPU : 0.010805 kWh
[codecarbon INFO @ 11:18:01] 0.011703 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:01] Energy consumed for RAM : 0.001657 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:01] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:01] Energy consumed for All CPU : 0.020120 kWh
[codecarbon INFO @ 11:18:01] 0.021778 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:02] Energy consumed for RAM : 0.001646 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:02] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:02] Energy consumed for All CPU : 0.019872 kWh
[codecarbon INFO @ 11:18:02] 0.021518 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:02] Energy consumed for RAM : 0.001996 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:02] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:02] Energy consumed for All CPU : 0.024119 kWh
[codecarbon INFO @ 11:18:02] 0.026115 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:02] Energy consumed for RAM : 0.001917 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:02] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:02] Energy consumed for All CPU : 0.023228 kWh
[codecarbon INFO @ 11:18:02] 0.025145 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:02] Energy consumed for RAM : 0.000071 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:02] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:02] Energy consumed for All CPU : 0.000861 kWh
[codecarbon INFO @ 11:18:02] 0.000932 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:02] Energy consumed for RAM : 0.000176 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:02] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:02] Energy consumed for All CPU : 0.002124 kWh
[codecarbon INFO @ 11:18:02] 0.002300 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:02] 0.016205 g.CO2eq/s mean an estimation of 511.028007199515 kg.CO2eq/year
[codecarbon INFO @ 11:18:02] Energy consumed for RAM : 0.000901 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:02] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:02] Energy consumed for All CPU : 0.010838 kWh
[codecarbon INFO @ 11:18:02] 0.011739 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:02] Energy consumed for RAM : 0.001660 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:02] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:02] Energy consumed for All CPU : 0.020153 kWh
[codecarbon INFO @ 11:18:02] 0.021814 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:03] Energy consumed for RAM : 0.001649 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:03] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:03] Energy consumed for All CPU : 0.019905 kWh
[codecarbon INFO @ 11:18:03] 0.021554 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:03] Energy consumed for RAM : 0.001999 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:03] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:03] Energy consumed for All CPU : 0.024152 kWh
[codecarbon INFO @ 11:18:03] 0.026152 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:03] Energy consumed for RAM : 0.001920 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:03] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:03] Energy consumed for All CPU : 0.023261 kWh
[codecarbon INFO @ 11:18:03] 0.025181 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:03] Energy consumed for RAM : 0.000074 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:03] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:03] Energy consumed for All CPU : 0.000894 kWh
[codecarbon INFO @ 11:18:03] 0.000968 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:03] Energy consumed for RAM : 0.000179 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:03] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:03] Energy consumed for All CPU : 0.002157 kWh
[codecarbon INFO @ 11:18:03] 0.002336 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:03] Energy consumed for RAM : 0.000904 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:03] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:03] Energy consumed for All CPU : 0.010871 kWh
[codecarbon INFO @ 11:18:03] 0.011775 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:03] Energy consumed for RAM : 0.001663 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:03] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:03] Energy consumed for All CPU : 0.020186 kWh
[codecarbon INFO @ 11:18:03] 0.021849 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:03] 0.016196 g.CO2eq/s mean an estimation of 510.75415728117224 kg.CO2eq/year
[codecarbon INFO @ 11:18:04] Energy consumed for RAM : 0.001652 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:04] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:04] Energy consumed for All CPU : 0.019938 kWh
[codecarbon INFO @ 11:18:04] Energy consumed for RAM : 0.002002 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:04] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:04] 0.021590 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:04] Energy consumed for All CPU : 0.024186 kWh
[codecarbon INFO @ 11:18:04] 0.026188 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:04] Energy consumed for RAM : 0.001923 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:04] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:04] Energy consumed for All CPU : 0.023294 kWh
[codecarbon INFO @ 11:18:04] 0.025216 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:04] Energy consumed for RAM : 0.000077 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:04] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:04] Energy consumed for All CPU : 0.000928 kWh
[codecarbon INFO @ 11:18:04] 0.001005 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:04] Energy consumed for RAM : 0.000182 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:18:04] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:18:04] Energy consumed for All CPU : 0.002190 kWh
[codecarbon INFO @ 11:18:04] 0.002372 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:18:04] Energy consumed for RAM : 0.000907 kWh. RAM Power : 10.0 W

=== CodeCarbon Tracking Summary ===
Project: demo_experiment
Output CSV: /gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emissions_pandas.csv

Average rating per author

In [ ]:
# Initialize the tracker with detailed logging
tracker = EmissionsTracker(
    project_name="demo_experiment",
    output_dir=log_dir,
    measure_power_secs=1,        # frequency of power measurement
    log_level="info",            # ensures detailed console + file logs
    save_to_file=True,           # ensure CSV file is written
)

# Start tracking
tracker.start()

# Simulate a computation workload
for _ in range(1000):
    a = np.random.rand(500, 500)
    b = np.random.rand(500, 500)
    np.dot(a, b)



# Si un auteur a plusieurs noms dans une cellule, on explode pour avoir une ligne par auteur
authors_exploded = book_df.assign(authors=book_df['authors'].str.split(', ')).explode('authors')

# Calcul de la moyenne par auteur
avg_rating_per_author = authors_exploded.groupby('authors')['review/score'].mean().sort_values(ascending=False)

print("Average rating per author:")
print(avg_rating_per_author.head(10))  # top 10

# Stop tracking
emissions = tracker.stop()

# Print summary
print("\n=== CodeCarbon Tracking Summary ===")
print(f"Project: {tracker._project_name}")
print(f"Output CSV: {os.path.join(log_dir, 'emissions_pandas.csv')}")

[codecarbon WARNING @ 11:22:02] Multiple instances of codecarbon are allowed to run at the same time.
[codecarbon INFO @ 11:22:02] [setup] RAM Tracking...
[codecarbon INFO @ 11:22:02] [setup] CPU Tracking...
[codecarbon INFO @ 11:22:02] Energy consumed for RAM : 0.002320 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:02] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:02] Energy consumed for All CPU : 0.028090 kWh
[codecarbon INFO @ 11:22:02] 0.030410 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:02] Energy consumed for RAM : 0.002659 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:02] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:02] Energy consumed for All CPU : 0.032090 kWh
[codecarbon INFO @ 11:22:02] 0.034749 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:02] Energy consumed for RAM : 0.002308 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:02] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:02] Energy consumed for All CPU : 0.027836 kWh
[codecarbon INFO @ 11:22:02] 0.030144 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:02] Energy consumed for RAM : 0.002579 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:02] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:02] Energy consumed for All CPU : 0.031191 kWh
[codecarbon INFO @ 11:22:02] 0.033770 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:02] Energy consumed for RAM : 0.000839 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:02] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:02] Energy consumed for All CPU : 0.010097 kWh
[codecarbon INFO @ 11:22:02] 0.010936 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:02] 0.016296 g.CO2eq/s mean an estimation of 513.9251956032006 kg.CO2eq/year
[codecarbon INFO @ 11:22:02] Energy consumed for RAM : 0.001564 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:02] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:02] Energy consumed for All CPU : 0.018807 kWh
[codecarbon INFO @ 11:22:03] 0.020370 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon WARNING @ 11:22:03] No CPU tracking mode found. Falling back on estimation based on TDP for CPU.
 Linux OS detected: Please ensure RAPL files exist at /sys/class/powercap/intel-rapl/subsystem to measure CPU

[codecarbon INFO @ 11:22:03] CPU Model on constant consumption mode: AMD EPYC 7B12
[codecarbon WARNING @ 11:22:03] No CPU tracking mode found. Falling back on CPU constant mode.
[codecarbon INFO @ 11:22:03] [setup] GPU Tracking...
[codecarbon INFO @ 11:22:03] No GPU found.
[codecarbon INFO @ 11:22:03] The below tracking methods have been set up:
                RAM Tracking Method: RAM power estimation model
                CPU Tracking Method: global constant
                GPU Tracking Method: Unspecified

[codecarbon INFO @ 11:22:03] >>> Tracker's metadata:
[codecarbon INFO @ 11:22:03]   Platform system: Linux-6.6.105+-x86_64-with-glibc2.35
[codecarbon INFO @ 11:22:03]   Python version: 3.12.12
[codecarbon INFO @ 11:22:03]   CodeCarbon version: 3.0.8
[codecarbon INFO @ 11:22:03]   Available RAM : 12.671 GB
[codecarbon INFO @ 11:22:03]   CPU count: 2 thread(s) in 1 physical CPU(s)
[codecarbon INFO @ 11:22:03]   CPU model: AMD EPYC 7B12
[codecarbon INFO @ 11:22:03]   GPU count: None
[codecarbon INFO @ 11:22:03]   GPU model: None
[codecarbon INFO @ 11:22:03] Energy consumed for RAM : 0.002323 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:03] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:03] Energy consumed for All CPU : 0.028123 kWh
[codecarbon INFO @ 11:22:03] 0.030446 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:03] Emissions data (if any) will be saved to file /gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emissions.csv
[codecarbon INFO @ 11:22:03] Energy consumed for RAM : 0.002662 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:03] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:03] Energy consumed for All CPU : 0.032123 kWh
[codecarbon INFO @ 11:22:03] 0.034785 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:03] Energy consumed for RAM : 0.002311 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:03] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:03] Energy consumed for All CPU : 0.027870 kWh
[codecarbon INFO @ 11:22:03] Energy consumed for RAM : 0.002581 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:03] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:03] 0.030181 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:03] Energy consumed for All CPU : 0.031224 kWh
[codecarbon INFO @ 11:22:03] 0.033806 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:03] Energy consumed for RAM : 0.000842 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:03] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:03] Energy consumed for All CPU : 0.010130 kWh
[codecarbon INFO @ 11:22:03] 0.010971 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:04] Energy consumed for RAM : 0.001566 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:04] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:04] Energy consumed for All CPU : 0.018840 kWh
[codecarbon INFO @ 11:22:04] 0.020407 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:04] Energy consumed for RAM : 0.002325 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:04] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:04] Energy consumed for All CPU : 0.028156 kWh
[codecarbon INFO @ 11:22:04] 0.030482 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:04] 0.016288 g.CO2eq/s mean an estimation of 513.6467989756379 kg.CO2eq/year
[codecarbon INFO @ 11:22:04] Energy consumed for RAM : 0.000003 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:04] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:04] Energy consumed for All CPU : 0.000033 kWh
[codecarbon INFO @ 11:22:04] 0.000036 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:04] Energy consumed for RAM : 0.002664 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:04] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:04] Energy consumed for All CPU : 0.032157 kWh
[codecarbon INFO @ 11:22:04] 0.034821 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:04] Energy consumed for RAM : 0.002314 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:04] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:04] Energy consumed for All CPU : 0.027902 kWh
[codecarbon INFO @ 11:22:04] 0.030216 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:04] Energy consumed for RAM : 0.002584 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:04] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:04] Energy consumed for All CPU : 0.031257 kWh
[codecarbon INFO @ 11:22:04] 0.033841 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:04] Energy consumed for RAM : 0.000844 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:04] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:04] Energy consumed for All CPU : 0.010163 kWh
[codecarbon INFO @ 11:22:04] 0.011007 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:05] Energy consumed for RAM : 0.001569 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:05] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:05] Energy consumed for All CPU : 0.018873 kWh
[codecarbon INFO @ 11:22:05] 0.020442 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:05] 0.016293 g.CO2eq/s mean an estimation of 513.8209540550564 kg.CO2eq/year
[codecarbon INFO @ 11:22:05] Energy consumed for RAM : 0.002328 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:05] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:05] Energy consumed for All CPU : 0.028190 kWh
[codecarbon INFO @ 11:22:05] 0.030518 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:05] Energy consumed for RAM : 0.000006 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:05] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:05] Energy consumed for All CPU : 0.000067 kWh
[codecarbon INFO @ 11:22:05] 0.000072 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:05] Energy consumed for RAM : 0.002667 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:05] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:05] Energy consumed for All CPU : 0.032190 kWh
[codecarbon INFO @ 11:22:05] 0.034857 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:05] Energy consumed for RAM : 0.002316 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:05] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:05] Energy consumed for All CPU : 0.027936 kWh
[codecarbon INFO @ 11:22:05] 0.030252 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:05] Energy consumed for RAM : 0.002587 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:05] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:05] Energy consumed for All CPU : 0.031290 kWh
[codecarbon INFO @ 11:22:05] 0.033877 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:05] Energy consumed for RAM : 0.000847 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:05] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:05] Energy consumed for All CPU : 0.010197 kWh
[codecarbon INFO @ 11:22:05] 0.011044 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:06] Energy consumed for RAM : 0.001572 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:06] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:06] Energy consumed for All CPU : 0.018907 kWh
[codecarbon INFO @ 11:22:06] 0.020478 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:06] Energy consumed for RAM : 0.002331 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:06] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:06] Energy consumed for All CPU : 0.028223 kWh
[codecarbon INFO @ 11:22:06] 0.030554 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:06] Energy consumed for RAM : 0.000008 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:06] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:06] Energy consumed for All CPU : 0.000100 kWh
[codecarbon INFO @ 11:22:06] 0.000108 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:06] Energy consumed for RAM : 0.002670 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:06] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:06] Energy consumed for All CPU : 0.032223 kWh
[codecarbon INFO @ 11:22:06] 0.034893 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:06] Energy consumed for RAM : 0.002319 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:06] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:06] Energy consumed for All CPU : 0.027969 kWh
[codecarbon INFO @ 11:22:06] 0.030288 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:06] Energy consumed for RAM : 0.002590 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:06] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:06] Energy consumed for All CPU : 0.031324 kWh
[codecarbon INFO @ 11:22:06] 0.033913 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:06] 0.016215 g.CO2eq/s mean an estimation of 511.3714675574384 kg.CO2eq/year
[codecarbon INFO @ 11:22:06] Energy consumed for RAM : 0.000850 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:06] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:06] Energy consumed for All CPU : 0.010230 kWh
[codecarbon INFO @ 11:22:06] 0.011079 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:07] Energy consumed for RAM : 0.001575 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:07] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:07] Energy consumed for All CPU : 0.018940 kWh
[codecarbon INFO @ 11:22:07] 0.020514 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:07] Energy consumed for RAM : 0.002334 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:07] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:07] Energy consumed for All CPU : 0.028256 kWh
[codecarbon INFO @ 11:22:07] 0.030590 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:07] Energy consumed for RAM : 0.000011 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:07] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:07] Energy consumed for All CPU : 0.000133 kWh
[codecarbon INFO @ 11:22:07] 0.000144 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:07] Energy consumed for RAM : 0.002673 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:07] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:07] Energy consumed for All CPU : 0.032256 kWh
[codecarbon INFO @ 11:22:07] 0.034929 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:07] 0.016250 g.CO2eq/s mean an estimation of 512.4557936142536 kg.CO2eq/year
[codecarbon INFO @ 11:22:07] Energy consumed for RAM : 0.002322 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:07] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:07] Energy consumed for All CPU : 0.028002 kWh
[codecarbon INFO @ 11:22:07] 0.030324 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:07] Energy consumed for RAM : 0.002592 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:07] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:07] Energy consumed for All CPU : 0.031356 kWh
[codecarbon INFO @ 11:22:07] 0.033949 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:07] Energy consumed for RAM : 0.000853 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:07] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:07] Energy consumed for All CPU : 0.010263 kWh
[codecarbon INFO @ 11:22:07] 0.011115 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:08] Energy consumed for RAM : 0.001577 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:08] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:08] Energy consumed for All CPU : 0.018973 kWh
[codecarbon INFO @ 11:22:08] 0.020550 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:08] Energy consumed for RAM : 0.002336 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:08] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:08] Energy consumed for All CPU : 0.028289 kWh
[codecarbon INFO @ 11:22:08] 0.030626 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:08] Energy consumed for RAM : 0.000014 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:08] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:08] Energy consumed for All CPU : 0.000166 kWh
[codecarbon INFO @ 11:22:08] 0.000180 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:08] Energy consumed for RAM : 0.002675 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:08] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:08] Energy consumed for All CPU : 0.032289 kWh
[codecarbon INFO @ 11:22:08] 0.034965 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:08] Energy consumed for RAM : 0.002324 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:08] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:08] Energy consumed for All CPU : 0.028035 kWh
[codecarbon INFO @ 11:22:08] 0.030359 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:08] Energy consumed for RAM : 0.002595 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:08] 0.016190 g.CO2eq/s mean an estimation of 510.5724817279171 kg.CO2eq/year
[codecarbon INFO @ 11:22:08] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:08] Energy consumed for All CPU : 0.031390 kWh
[codecarbon INFO @ 11:22:08] 0.033985 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:08] Energy consumed for RAM : 0.000855 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:08] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:08] Energy consumed for All CPU : 0.010296 kWh
[codecarbon INFO @ 11:22:08] 0.011151 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:22:09] Energy consumed for RAM : 0.001580 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:22:09] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:22:09] Energy consumed for All CPU : 0.019006 kWh
[codecarbon INFO @ 11:22:09] 0.020586 kWh of electricity and 0.000000 L of water were used since the beginning.

Average rating per author:
Series([], Name: review/score, dtype: float64)

=== CodeCarbon Tracking Summary ===
Project: demo_experiment
Output CSV: /gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emissions_pandas.csv

 Number of reviews per publisher

In [ ]:
# Initialize the tracker with detailed logging
tracker = EmissionsTracker(
    project_name="demo_experiment",
    output_dir=log_dir,
    measure_power_secs=1,        # frequency of power measurement
    log_level="info",            # ensures detailed console + file logs
    save_to_file=True,           # ensure CSV file is written
)

# Start tracking
tracker.start()

# Simulate a computation workload
for _ in range(1000):
    a = np.random.rand(500, 500)
    b = np.random.rand(500, 500)
    np.dot(a, b)



reviews_per_publisher = book_df.groupby('publisher')['review/score'].count().sort_values(ascending=False)

print("\nNumber of reviews per publisher:")
print(reviews_per_publisher.head(10))

# Stop tracking
emissions = tracker.stop()

# Print summary
print("\n=== CodeCarbon Tracking Summary ===")
print(f"Project: {tracker._project_name}")
print(f"Output CSV: {os.path.join(log_dir, 'emissions_pandas.csv')}")

[codecarbon WARNING @ 11:23:21] Multiple instances of codecarbon are allowed to run at the same time.
[codecarbon INFO @ 11:23:21] [setup] RAM Tracking...
[codecarbon INFO @ 11:23:21] [setup] CPU Tracking...
[codecarbon INFO @ 11:23:21] Energy consumed for RAM : 0.002794 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:21] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:21] Energy consumed for All CPU : 0.033806 kWh
[codecarbon INFO @ 11:23:21] 0.036600 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:21] Energy consumed for RAM : 0.002524 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:21] Energy consumed for RAM : 0.002875 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:21] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:21] Energy consumed for All CPU : 0.034701 kWh
[codecarbon INFO @ 11:23:22] 0.037576 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:21] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:22] Energy consumed for All CPU : 0.030452 kWh
[codecarbon INFO @ 11:23:22] 0.032976 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:22] Energy consumed for RAM : 0.001781 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:22] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:22] Energy consumed for All CPU : 0.021436 kWh
[codecarbon INFO @ 11:23:22] 0.023217 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:22] Energy consumed for RAM : 0.002539 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:22] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:22] Energy consumed for All CPU : 0.030729 kWh
[codecarbon INFO @ 11:23:22] 0.033268 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:22] Energy consumed for RAM : 0.001055 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:22] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:22] Energy consumed for All CPU : 0.012729 kWh
[codecarbon INFO @ 11:23:22] 0.013784 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon WARNING @ 11:23:22] No CPU tracking mode found. Falling back on estimation based on TDP for CPU.
 Linux OS detected: Please ensure RAPL files exist at /sys/class/powercap/intel-rapl/subsystem to measure CPU

[codecarbon INFO @ 11:23:22] CPU Model on constant consumption mode: AMD EPYC 7B12
[codecarbon WARNING @ 11:23:22] No CPU tracking mode found. Falling back on CPU constant mode.
[codecarbon INFO @ 11:23:22] [setup] GPU Tracking...
[codecarbon INFO @ 11:23:22] No GPU found.
[codecarbon INFO @ 11:23:22] The below tracking methods have been set up:
                RAM Tracking Method: RAM power estimation model
                CPU Tracking Method: global constant
                GPU Tracking Method: Unspecified

[codecarbon INFO @ 11:23:22] >>> Tracker's metadata:
[codecarbon INFO @ 11:23:22]   Platform system: Linux-6.6.105+-x86_64-with-glibc2.35
[codecarbon INFO @ 11:23:22]   Python version: 3.12.12
[codecarbon INFO @ 11:23:22]   CodeCarbon version: 3.0.8
[codecarbon INFO @ 11:23:22]   Available RAM : 12.671 GB
[codecarbon INFO @ 11:23:22]   CPU count: 2 thread(s) in 1 physical CPU(s)
[codecarbon INFO @ 11:23:22]   CPU model: AMD EPYC 7B12
[codecarbon INFO @ 11:23:22]   GPU count: None
[codecarbon INFO @ 11:23:22]   GPU model: None
[codecarbon INFO @ 11:23:22] Emissions data (if any) will be saved to file /gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emissions.csv
[codecarbon INFO @ 11:23:22] Energy consumed for RAM : 0.002797 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:22] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:22] Energy consumed for All CPU : 0.033839 kWh
[codecarbon INFO @ 11:23:22] Energy consumed for RAM : 0.002877 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:22] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:22] Energy consumed for All CPU : 0.034734 kWh
[codecarbon INFO @ 11:23:22] 0.037611 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:22] Energy consumed for RAM : 0.002527 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:23] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:23] Energy consumed for All CPU : 0.030485 kWh
[codecarbon INFO @ 11:23:23] 0.033012 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:22] 0.036635 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:23] Energy consumed for RAM : 0.001783 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:23] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:23] Energy consumed for All CPU : 0.021469 kWh
[codecarbon INFO @ 11:23:23] 0.023253 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:23] Energy consumed for RAM : 0.002542 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:23] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:23] Energy consumed for All CPU : 0.030762 kWh
[codecarbon INFO @ 11:23:23] 0.033304 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:23] Energy consumed for RAM : 0.001058 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:23] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:23] Energy consumed for All CPU : 0.012762 kWh
[codecarbon INFO @ 11:23:23] 0.013820 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:23] 0.016279 g.CO2eq/s mean an estimation of 513.3803671472081 kg.CO2eq/year
[codecarbon INFO @ 11:23:23] Energy consumed for RAM : 0.000003 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:23] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:23] Energy consumed for All CPU : 0.000034 kWh
[codecarbon INFO @ 11:23:23] 0.000036 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:23] Energy consumed for RAM : 0.002799 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:23] Delta energy consumed for CPU with constant : 0.000032 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:23] Energy consumed for All CPU : 0.033871 kWh
[codecarbon INFO @ 11:23:23] 0.036670 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:23] Energy consumed for RAM : 0.002880 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:23] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:23] Energy consumed for All CPU : 0.034767 kWh
[codecarbon INFO @ 11:23:23] Energy consumed for RAM : 0.002530 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:23] 0.037647 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:24] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:24] Energy consumed for All CPU : 0.030519 kWh
[codecarbon INFO @ 11:23:24] 0.033048 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:24] Energy consumed for RAM : 0.001786 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:24] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:24] Energy consumed for All CPU : 0.021503 kWh
[codecarbon INFO @ 11:23:24] Energy consumed for RAM : 0.002544 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:24] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:24] Energy consumed for All CPU : 0.030795 kWh
[codecarbon INFO @ 11:23:24] 0.033339 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:24] 0.023289 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:24] Energy consumed for RAM : 0.001061 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:24] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:24] Energy consumed for All CPU : 0.012796 kWh
[codecarbon INFO @ 11:23:24] 0.013856 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:24] 0.016239 g.CO2eq/s mean an estimation of 512.1063508487827 kg.CO2eq/year
[codecarbon INFO @ 11:23:24] Energy consumed for RAM : 0.000006 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:24] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:24] Energy consumed for All CPU : 0.000067 kWh
[codecarbon INFO @ 11:23:24] 0.000072 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:24] Energy consumed for RAM : 0.002802 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:24] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:24] Energy consumed for All CPU : 0.033904 kWh
[codecarbon INFO @ 11:23:24] 0.036706 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:24] Energy consumed for RAM : 0.002883 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:24] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:24] Energy consumed for RAM : 0.002532 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:24] Energy consumed for All CPU : 0.034799 kWh
[codecarbon INFO @ 11:23:24] Delta energy consumed for CPU with constant : 0.000032 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:24] Energy consumed for All CPU : 0.030551 kWh
[codecarbon INFO @ 11:23:24] 0.037682 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:25] 0.033083 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:25] Energy consumed for RAM : 0.001789 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:25] Delta energy consumed for CPU with constant : 0.000032 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:25] Energy consumed for All CPU : 0.021535 kWh
[codecarbon INFO @ 11:23:25] 0.023324 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:25] Energy consumed for RAM : 0.002547 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:25] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:25] Energy consumed for All CPU : 0.030828 kWh
[codecarbon INFO @ 11:23:25] 0.033375 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:25] 0.016228 g.CO2eq/s mean an estimation of 511.7572092179475 kg.CO2eq/year
[codecarbon INFO @ 11:23:25] Energy consumed for RAM : 0.001063 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:25] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:25] Energy consumed for All CPU : 0.012828 kWh
[codecarbon INFO @ 11:23:25] 0.013892 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:25] Energy consumed for RAM : 0.000008 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:25] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:25] Energy consumed for All CPU : 0.000100 kWh
[codecarbon INFO @ 11:23:25] 0.000108 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:25] Energy consumed for RAM : 0.002805 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:25] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:25] Energy consumed for All CPU : 0.033937 kWh
[codecarbon INFO @ 11:23:25] 0.036742 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:25] Energy consumed for RAM : 0.002885 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:25] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:25] Energy consumed for RAM : 0.002535 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:26] Energy consumed for All CPU : 0.034832 kWh
[codecarbon INFO @ 11:23:26] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:26] Energy consumed for All CPU : 0.030584 kWh
[codecarbon INFO @ 11:23:26] 0.033119 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:26] 0.037718 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:26] Energy consumed for RAM : 0.001792 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:26] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:26] Energy consumed for All CPU : 0.021568 kWh
[codecarbon INFO @ 11:23:26] 0.023360 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:26] Energy consumed for RAM : 0.002550 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:26] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:26] Energy consumed for All CPU : 0.030861 kWh
[codecarbon INFO @ 11:23:26] 0.033411 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:26] Energy consumed for RAM : 0.001066 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:26] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:26] Energy consumed for All CPU : 0.012862 kWh
[codecarbon INFO @ 11:23:26] 0.013928 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:26] Energy consumed for RAM : 0.000011 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:26] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:26] Energy consumed for All CPU : 0.000133 kWh
[codecarbon INFO @ 11:23:26] 0.000144 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:26] Energy consumed for RAM : 0.002808 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:26] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:26] Energy consumed for All CPU : 0.033970 kWh
[codecarbon INFO @ 11:23:26] 0.036778 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:26] 0.016174 g.CO2eq/s mean an estimation of 510.0681321834927 kg.CO2eq/year
[codecarbon INFO @ 11:23:26] Energy consumed for RAM : 0.002888 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:26] Delta energy consumed for CPU with constant : 0.000032 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:26] Energy consumed for All CPU : 0.034865 kWh
[codecarbon INFO @ 11:23:26] 0.037753 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:27] Energy consumed for RAM : 0.002538 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:27] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:27] Energy consumed for All CPU : 0.030617 kWh
[codecarbon INFO @ 11:23:27] 0.033155 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:27] Energy consumed for RAM : 0.001794 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:27] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:27] Energy consumed for All CPU : 0.021601 kWh
[codecarbon INFO @ 11:23:27] 0.023396 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:27] Energy consumed for RAM : 0.002553 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:27] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:27] Energy consumed for All CPU : 0.030894 kWh
[codecarbon INFO @ 11:23:27] 0.033447 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:27] Energy consumed for RAM : 0.001069 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:27] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:27] Energy consumed for All CPU : 0.012895 kWh
[codecarbon INFO @ 11:23:27] 0.013964 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:27] Energy consumed for RAM : 0.000014 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:27] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:27] Energy consumed for All CPU : 0.000166 kWh
[codecarbon INFO @ 11:23:27] 0.000180 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:27] Energy consumed for RAM : 0.002810 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:27] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:27] Energy consumed for All CPU : 0.034003 kWh
[codecarbon INFO @ 11:23:27] 0.036814 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:27] Energy consumed for RAM : 0.002891 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:27] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:27] Energy consumed for All CPU : 0.034897 kWh
[codecarbon INFO @ 11:23:27] 0.037788 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:27] 0.016086 g.CO2eq/s mean an estimation of 507.2935912083486 kg.CO2eq/year
[codecarbon INFO @ 11:23:28] Energy consumed for RAM : 0.002540 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:28] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:28] Energy consumed for All CPU : 0.030650 kWh
[codecarbon INFO @ 11:23:28] 0.033191 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:28] Energy consumed for RAM : 0.001797 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:28] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:28] Energy consumed for All CPU : 0.021635 kWh
[codecarbon INFO @ 11:23:28] 0.023432 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:28] Energy consumed for RAM : 0.002555 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:28] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:28] Energy consumed for All CPU : 0.030928 kWh
[codecarbon INFO @ 11:23:28] 0.033483 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:28] Energy consumed for RAM : 0.001072 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:23:28] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:23:28] Energy consumed for All CPU : 0.012928 kWh
[codecarbon INFO @ 11:23:28] 0.014000 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:23:28] Energy consumed for RAM : 0.000017 kWh. RAM Power : 10.0 W

Number of reviews per publisher:
publisher
Unknown                782617
Penguin                137071
Simon and Schuster     118101
Harper Collins          84926
Random House            46241
Vintage                 41792
Courier Corporation     37589
HarperCollins           30218
Mariner Books           30154
Macmillan               29323
Name: review/score, dtype: int64

=== CodeCarbon Tracking Summary ===
Project: demo_experiment
Output CSV: /gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emissions_pandas.csv

Top 10 most-reviewed categories

In [ ]:
# Initialize the tracker with detailed logging
tracker = EmissionsTracker(
    project_name="demo_experiment",
    output_dir=log_dir,
    measure_power_secs=1,        # frequency of power measurement
    log_level="info",            # ensures detailed console + file logs
    save_to_file=True,           # ensure CSV file is written
)

# Start tracking
tracker.start()

# Simulate a computation workload
for _ in range(1000):
    a = np.random.rand(500, 500)
    b = np.random.rand(500, 500)
    np.dot(a, b)



# Exploser les catégories pour avoir une ligne par catégorie
categories_exploded = book_df.assign(categories=book_df['categories'].str.split(', ')).explode('categories')

# Compter le nombre de reviews par catégorie
top_categories = categories_exploded.groupby('categories')['review/score'].count().sort_values(ascending=False)

print("\nTop 10 most-reviewed categories:")
print(top_categories.head(10))

# Stop tracking
emissions = tracker.stop()

# Print summary
print("\n=== CodeCarbon Tracking Summary ===")
print(f"Project: {tracker._project_name}")
print(f"Output CSV: {os.path.join(log_dir, 'emissions_pandas.csv')}")

[codecarbon WARNING @ 11:25:15] Multiple instances of codecarbon are allowed to run at the same time.
[codecarbon INFO @ 11:25:15] Energy consumed for RAM : 0.002093 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:15] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:15] Energy consumed for All CPU : 0.025190 kWh
[codecarbon INFO @ 11:25:15] [setup] RAM Tracking...
[codecarbon INFO @ 11:25:15] [setup] CPU Tracking...
[codecarbon INFO @ 11:25:15] 0.027283 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:15] Energy consumed for RAM : 0.002852 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:15] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:15] Energy consumed for All CPU : 0.034489 kWh
[codecarbon INFO @ 11:25:15] 0.037341 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:15] Energy consumed for RAM : 0.001368 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:15] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:15] Energy consumed for All CPU : 0.016487 kWh
[codecarbon INFO @ 11:25:15] 0.017855 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:15] 0.016279 g.CO2eq/s mean an estimation of 513.3804886418554 kg.CO2eq/year
[codecarbon INFO @ 11:25:16] Energy consumed for RAM : 0.003109 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:16] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:16] Energy consumed for All CPU : 0.037594 kWh
[codecarbon INFO @ 11:25:16] 0.040704 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:16] Energy consumed for RAM : 0.003189 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:16] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:16] Energy consumed for All CPU : 0.038485 kWh
[codecarbon INFO @ 11:25:16] 0.041674 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:16] Energy consumed for RAM : 0.002839 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:16] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:16] Energy consumed for All CPU : 0.034238 kWh
[codecarbon INFO @ 11:25:16] 0.037077 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:16] Energy consumed for RAM : 0.002096 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:16] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:16] Energy consumed for All CPU : 0.025224 kWh
[codecarbon INFO @ 11:25:16] 0.027319 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:16] Energy consumed for RAM : 0.002854 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:16] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:16] Energy consumed for All CPU : 0.034523 kWh
[codecarbon INFO @ 11:25:16] 0.037377 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:16] 0.016293 g.CO2eq/s mean an estimation of 513.8110624009348 kg.CO2eq/year
[codecarbon INFO @ 11:25:16] Energy consumed for RAM : 0.001370 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:16] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:16] Energy consumed for All CPU : 0.016521 kWh
[codecarbon INFO @ 11:25:16] 0.017891 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon WARNING @ 11:25:16] No CPU tracking mode found. Falling back on estimation based on TDP for CPU.
 Linux OS detected: Please ensure RAPL files exist at /sys/class/powercap/intel-rapl/subsystem to measure CPU

[codecarbon INFO @ 11:25:16] CPU Model on constant consumption mode: AMD EPYC 7B12
[codecarbon WARNING @ 11:25:16] No CPU tracking mode found. Falling back on CPU constant mode.
[codecarbon INFO @ 11:25:16] [setup] GPU Tracking...
[codecarbon INFO @ 11:25:16] No GPU found.
[codecarbon INFO @ 11:25:16] The below tracking methods have been set up:
                RAM Tracking Method: RAM power estimation model
                CPU Tracking Method: global constant
                GPU Tracking Method: Unspecified

[codecarbon INFO @ 11:25:16] >>> Tracker's metadata:
[codecarbon INFO @ 11:25:16]   Platform system: Linux-6.6.105+-x86_64-with-glibc2.35
[codecarbon INFO @ 11:25:16]   Python version: 3.12.12
[codecarbon INFO @ 11:25:16]   CodeCarbon version: 3.0.8
[codecarbon INFO @ 11:25:16]   Available RAM : 12.671 GB
[codecarbon INFO @ 11:25:16]   CPU count: 2 thread(s) in 1 physical CPU(s)
[codecarbon INFO @ 11:25:16]   CPU model: AMD EPYC 7B12
[codecarbon INFO @ 11:25:16]   GPU count: None
[codecarbon INFO @ 11:25:16]   GPU model: None
[codecarbon INFO @ 11:25:16] Emissions data (if any) will be saved to file /gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emissions.csv
[codecarbon INFO @ 11:25:17] Energy consumed for RAM : 0.003112 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:17] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:17] Energy consumed for All CPU : 0.037628 kWh
[codecarbon INFO @ 11:25:17] 0.040739 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:17] Energy consumed for RAM : 0.003192 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:17] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:17] Energy consumed for All CPU : 0.038519 kWh
[codecarbon INFO @ 11:25:17] Energy consumed for RAM : 0.002842 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:17] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:17] 0.041711 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:17] Energy consumed for All CPU : 0.034272 kWh
[codecarbon INFO @ 11:25:17] 0.037113 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:17] Energy consumed for RAM : 0.002098 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:17] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:17] Energy consumed for All CPU : 0.025257 kWh
[codecarbon INFO @ 11:25:17] 0.027355 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:17] 0.016274 g.CO2eq/s mean an estimation of 513.2026393354358 kg.CO2eq/year
[codecarbon INFO @ 11:25:17] Energy consumed for RAM : 0.002857 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:17] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:17] Energy consumed for All CPU : 0.034556 kWh
[codecarbon INFO @ 11:25:17] 0.037413 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:17] Energy consumed for RAM : 0.001373 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:17] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:17] Energy consumed for All CPU : 0.016554 kWh
[codecarbon INFO @ 11:25:17] 0.017927 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:17] Energy consumed for RAM : 0.000003 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:17] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:17] Energy consumed for All CPU : 0.000034 kWh
[codecarbon INFO @ 11:25:17] 0.000036 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:18] Energy consumed for RAM : 0.003115 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:18] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:18] Energy consumed for All CPU : 0.037661 kWh
[codecarbon INFO @ 11:25:18] 0.040775 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:18] Energy consumed for RAM : 0.003195 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:18] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:18] Energy consumed for All CPU : 0.038551 kWh
[codecarbon INFO @ 11:25:18] 0.041746 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:18] Energy consumed for RAM : 0.002844 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:18] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:18] Energy consumed for All CPU : 0.034305 kWh
[codecarbon INFO @ 11:25:18] 0.037149 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:18] Energy consumed for RAM : 0.002101 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:18] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:18] Energy consumed for All CPU : 0.025290 kWh
[codecarbon INFO @ 11:25:18] 0.027391 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:18] Energy consumed for RAM : 0.002860 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:18] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:18] Energy consumed for All CPU : 0.034589 kWh
[codecarbon INFO @ 11:25:18] 0.037449 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:18] Energy consumed for RAM : 0.001376 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:18] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:18] Energy consumed for All CPU : 0.016587 kWh
[codecarbon INFO @ 11:25:18] 0.017963 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:18] Energy consumed for RAM : 0.000006 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:18] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:18] Energy consumed for All CPU : 0.000067 kWh
[codecarbon INFO @ 11:25:18] 0.000073 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:19] Energy consumed for RAM : 0.003117 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:19] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:19] Energy consumed for All CPU : 0.037694 kWh
[codecarbon INFO @ 11:25:19] 0.040811 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:19] Energy consumed for RAM : 0.003197 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:19] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:19] Energy consumed for All CPU : 0.038584 kWh
[codecarbon INFO @ 11:25:19] 0.041782 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:19] 0.016260 g.CO2eq/s mean an estimation of 512.7828018204119 kg.CO2eq/year
[codecarbon INFO @ 11:25:19] Energy consumed for RAM : 0.002847 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:19] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:19] Energy consumed for All CPU : 0.034338 kWh
[codecarbon INFO @ 11:25:19] 0.037185 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:19] Energy consumed for RAM : 0.002104 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:19] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:19] Energy consumed for All CPU : 0.025323 kWh
[codecarbon INFO @ 11:25:19] 0.027427 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:19] Energy consumed for RAM : 0.002863 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:19] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:19] Energy consumed for All CPU : 0.034622 kWh
[codecarbon INFO @ 11:25:19] 0.037485 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:19] Energy consumed for RAM : 0.001379 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:19] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:19] Energy consumed for All CPU : 0.016620 kWh
[codecarbon INFO @ 11:25:19] 0.017999 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:19] Energy consumed for RAM : 0.000008 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:19] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:19] Energy consumed for All CPU : 0.000100 kWh
[codecarbon INFO @ 11:25:20] 0.000108 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:20] Energy consumed for RAM : 0.003120 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:20] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:20] Energy consumed for All CPU : 0.037727 kWh
[codecarbon INFO @ 11:25:20] 0.040847 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:20] Energy consumed for RAM : 0.003200 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:20] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:20] Energy consumed for All CPU : 0.038618 kWh
[codecarbon INFO @ 11:25:20] 0.041818 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:20] Energy consumed for RAM : 0.002850 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:20] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:20] Energy consumed for All CPU : 0.034372 kWh
[codecarbon INFO @ 11:25:20] 0.037222 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:20] 0.016180 g.CO2eq/s mean an estimation of 510.23807278866485 kg.CO2eq/year
[codecarbon INFO @ 11:25:20] Energy consumed for RAM : 0.002107 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:20] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:20] Energy consumed for All CPU : 0.025356 kWh
[codecarbon INFO @ 11:25:20] 0.027463 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:20] Energy consumed for RAM : 0.002865 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:20] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:20] Energy consumed for All CPU : 0.034655 kWh
[codecarbon INFO @ 11:25:20] 0.037521 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:20] Energy consumed for RAM : 0.001381 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:20] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:20] Energy consumed for All CPU : 0.016654 kWh
[codecarbon INFO @ 11:25:20] 0.018035 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:20] Energy consumed for RAM : 0.000011 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:20] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:20] Energy consumed for All CPU : 0.000133 kWh
[codecarbon INFO @ 11:25:20] 0.000144 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:21] Energy consumed for RAM : 0.003123 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:21] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:21] Energy consumed for All CPU : 0.037760 kWh
[codecarbon INFO @ 11:25:21] 0.040883 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:21] Energy consumed for RAM : 0.003203 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:21] Delta energy consumed for CPU with constant : 0.000032 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:21] Energy consumed for All CPU : 0.038650 kWh
[codecarbon INFO @ 11:25:21] 0.041853 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:21] Energy consumed for RAM : 0.002853 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:21] Delta energy consumed for CPU with constant : 0.000032 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:21] Energy consumed for All CPU : 0.034404 kWh
[codecarbon INFO @ 11:25:21] 0.037257 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:21] 0.016204 g.CO2eq/s mean an estimation of 511.0201121772427 kg.CO2eq/year
[codecarbon INFO @ 11:25:21] Energy consumed for RAM : 0.002109 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:21] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:21] Energy consumed for All CPU : 0.025389 kWh
[codecarbon INFO @ 11:25:21] 0.027498 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:21] Energy consumed for RAM : 0.002868 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:21] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:21] Energy consumed for All CPU : 0.034688 kWh
[codecarbon INFO @ 11:25:21] 0.037556 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:21] Energy consumed for RAM : 0.001384 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:21] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:21] Energy consumed for All CPU : 0.016686 kWh
[codecarbon INFO @ 11:25:21] 0.018070 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:21] Energy consumed for RAM : 0.000014 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:21] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:21] Energy consumed for All CPU : 0.000166 kWh
[codecarbon INFO @ 11:25:22] 0.000180 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:22] Energy consumed for RAM : 0.003126 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:22] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:22] Energy consumed for All CPU : 0.037793 kWh
[codecarbon INFO @ 11:25:22] 0.040919 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:22] Energy consumed for RAM : 0.003206 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:22] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:22] Energy consumed for All CPU : 0.038683 kWh
[codecarbon INFO @ 11:25:22] 0.041889 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:25:22] Energy consumed for RAM : 0.002855 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:25:22] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:25:22] Energy consumed for All CPU : 0.034437 kWh
[codecarbon INFO @ 11:25:22] 0.037292 kWh of electricity and 0.000000 L of water were used since the beginning.

Top 10 most-reviewed categories:
Series([], Name: review/score, dtype: int64)

=== CodeCarbon Tracking Summary ===
Project: demo_experiment
Output CSV: /gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emissions_pandas.csv

2. **Text processing**

Average review length

In [ ]:
# Initialize the tracker with detailed logging
tracker = EmissionsTracker(
    project_name="demo_experiment",
    output_dir=log_dir,
    measure_power_secs=1,        # frequency of power measurement
    log_level="info",            # ensures detailed console + file logs
    save_to_file=True,           # ensure CSV file is written
)

# Start tracking
tracker.start()

# Simulate a computation workload
for _ in range(1000):
    a = np.random.rand(500, 500)
    b = np.random.rand(500, 500)
    np.dot(a, b)




# Ajouter une colonne avec la longueur de chaque review (nombre de caractères)
book_df['review_length'] = book_df['review/text'].astype(str).apply(len)

# Calculer la longueur moyenne
average_review_length = book_df['review_length'].mean()

print(f"📏 Average review length: {average_review_length:.2f} characters")

# Stop tracking
emissions = tracker.stop()

# Print summary
print("\n=== CodeCarbon Tracking Summary ===")
print(f"Project: {tracker._project_name}")
print(f"Output CSV: {os.path.join(log_dir, 'emissions_pandas.csv')}")

[codecarbon WARNING @ 11:26:10] Multiple instances of codecarbon are allowed to run at the same time.
[codecarbon INFO @ 11:26:10] [setup] RAM Tracking...
[codecarbon INFO @ 11:26:10] [setup] CPU Tracking...
[codecarbon INFO @ 11:26:10] Energy consumed for RAM : 0.003337 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:10] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:10] Energy consumed for All CPU : 0.040268 kWh
[codecarbon INFO @ 11:26:10] 0.043605 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:10] Energy consumed for RAM : 0.002984 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:10] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:10] Energy consumed for All CPU : 0.036012 kWh
[codecarbon INFO @ 11:26:10] 0.038997 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:10] Energy consumed for RAM : 0.003257 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:10] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:10] Energy consumed for All CPU : 0.039390 kWh
[codecarbon INFO @ 11:26:10] 0.042647 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:10] Energy consumed for RAM : 0.002244 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:10] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:10] Energy consumed for All CPU : 0.027018 kWh
[codecarbon INFO @ 11:26:10] 0.029263 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:11] Energy consumed for RAM : 0.003003 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:11] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:11] Energy consumed for All CPU : 0.036318 kWh
[codecarbon INFO @ 11:26:11] 0.039321 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:11] Energy consumed for RAM : 0.001519 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:11] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:11] Energy consumed for All CPU : 0.018313 kWh
[codecarbon INFO @ 11:26:11] 0.019831 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:11] Energy consumed for RAM : 0.003340 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:11] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:11] Energy consumed for All CPU : 0.040301 kWh
[codecarbon INFO @ 11:26:11] 0.043641 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:11] Energy consumed for RAM : 0.002987 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:11] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:11] Energy consumed for All CPU : 0.036045 kWh
[codecarbon INFO @ 11:26:11] 0.039033 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:11] Energy consumed for RAM : 0.003260 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:11] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:11] Energy consumed for All CPU : 0.039423 kWh
[codecarbon INFO @ 11:26:11] 0.042683 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon WARNING @ 11:26:11] No CPU tracking mode found. Falling back on estimation based on TDP for CPU.
 Linux OS detected: Please ensure RAPL files exist at /sys/class/powercap/intel-rapl/subsystem to measure CPU

[codecarbon INFO @ 11:26:11] CPU Model on constant consumption mode: AMD EPYC 7B12
[codecarbon WARNING @ 11:26:11] No CPU tracking mode found. Falling back on CPU constant mode.
[codecarbon INFO @ 11:26:11] [setup] GPU Tracking...
[codecarbon INFO @ 11:26:11] No GPU found.
[codecarbon INFO @ 11:26:11] The below tracking methods have been set up:
                RAM Tracking Method: RAM power estimation model
                CPU Tracking Method: global constant
                GPU Tracking Method: Unspecified

[codecarbon INFO @ 11:26:11] >>> Tracker's metadata:
[codecarbon INFO @ 11:26:11]   Platform system: Linux-6.6.105+-x86_64-with-glibc2.35
[codecarbon INFO @ 11:26:11]   Python version: 3.12.12
[codecarbon INFO @ 11:26:11]   CodeCarbon version: 3.0.8
[codecarbon INFO @ 11:26:11]   Available RAM : 12.671 GB
[codecarbon INFO @ 11:26:11]   CPU count: 2 thread(s) in 1 physical CPU(s)
[codecarbon INFO @ 11:26:11]   CPU model: AMD EPYC 7B12
[codecarbon INFO @ 11:26:11]   GPU count: None
[codecarbon INFO @ 11:26:11]   GPU model: None
[codecarbon INFO @ 11:26:11] Emissions data (if any) will be saved to file /gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emissions.csv
[codecarbon INFO @ 11:26:11] Energy consumed for RAM : 0.002247 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:11] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:11] Energy consumed for All CPU : 0.027052 kWh
[codecarbon INFO @ 11:26:11] 0.029299 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:12] Energy consumed for RAM : 0.003006 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:12] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:12] Energy consumed for All CPU : 0.036351 kWh
[codecarbon INFO @ 11:26:12] 0.039357 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:12] Energy consumed for RAM : 0.001521 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:12] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:12] Energy consumed for All CPU : 0.018346 kWh
[codecarbon INFO @ 11:26:12] 0.019868 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:12] 0.016257 g.CO2eq/s mean an estimation of 512.6783770482335 kg.CO2eq/year
[codecarbon INFO @ 11:26:12] Energy consumed for RAM : 0.003342 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:12] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:12] Energy consumed for All CPU : 0.040335 kWh
[codecarbon INFO @ 11:26:12] 0.043677 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:12] Energy consumed for RAM : 0.002990 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:12] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:12] Energy consumed for RAM : 0.003263 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:12] Energy consumed for All CPU : 0.036079 kWh
[codecarbon INFO @ 11:26:12] 0.039069 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:12] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:12] Energy consumed for All CPU : 0.039457 kWh
[codecarbon INFO @ 11:26:12] 0.042720 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:12] Energy consumed for RAM : 0.000003 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:12] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:12] Energy consumed for All CPU : 0.000034 kWh
[codecarbon INFO @ 11:26:12] 0.000036 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:12] Energy consumed for RAM : 0.002250 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:12] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:12] Energy consumed for All CPU : 0.027085 kWh
[codecarbon INFO @ 11:26:12] 0.029335 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:13] Energy consumed for RAM : 0.003008 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:13] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:13] Energy consumed for All CPU : 0.036384 kWh
[codecarbon INFO @ 11:26:13] 0.039393 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:13] 0.016274 g.CO2eq/s mean an estimation of 513.2138843954806 kg.CO2eq/year
[codecarbon INFO @ 11:26:13] Energy consumed for RAM : 0.001524 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:13] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:13] Energy consumed for All CPU : 0.018379 kWh
[codecarbon INFO @ 11:26:13] 0.019903 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:13] Energy consumed for RAM : 0.003345 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:13] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:13] Energy consumed for All CPU : 0.040368 kWh
[codecarbon INFO @ 11:26:13] 0.043713 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:13] Energy consumed for RAM : 0.002993 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:13] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:13] Energy consumed for All CPU : 0.036111 kWh
[codecarbon INFO @ 11:26:13] 0.039104 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:13] Energy consumed for RAM : 0.003266 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:13] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:13] Energy consumed for All CPU : 0.039489 kWh
[codecarbon INFO @ 11:26:13] 0.042755 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:13] Energy consumed for RAM : 0.000006 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:13] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:13] Energy consumed for All CPU : 0.000067 kWh
[codecarbon INFO @ 11:26:13] 0.000072 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:13] Energy consumed for RAM : 0.002253 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:13] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:13] Energy consumed for All CPU : 0.027118 kWh
[codecarbon INFO @ 11:26:13] 0.029371 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:13] 0.016287 g.CO2eq/s mean an estimation of 513.6294733999937 kg.CO2eq/year
[codecarbon INFO @ 11:26:14] Energy consumed for RAM : 0.003011 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:14] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:14] Energy consumed for All CPU : 0.036418 kWh
[codecarbon INFO @ 11:26:14] 0.039429 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:14] Energy consumed for RAM : 0.001527 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:14] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:14] Energy consumed for All CPU : 0.018412 kWh
[codecarbon INFO @ 11:26:14] 0.019939 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:14] Energy consumed for RAM : 0.003348 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:14] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:14] Energy consumed for All CPU : 0.040401 kWh
[codecarbon INFO @ 11:26:14] 0.043749 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:14] Energy consumed for RAM : 0.002995 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:14] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:14] Energy consumed for All CPU : 0.036145 kWh
[codecarbon INFO @ 11:26:14] 0.039140 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:14] Energy consumed for RAM : 0.003268 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:14] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:14] Energy consumed for All CPU : 0.039523 kWh
[codecarbon INFO @ 11:26:14] 0.042791 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:14] Energy consumed for RAM : 0.000008 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:14] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:14] Energy consumed for All CPU : 0.000100 kWh
[codecarbon INFO @ 11:26:14] 0.000108 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:14] Energy consumed for RAM : 0.002255 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:14] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:14] Energy consumed for All CPU : 0.027151 kWh
[codecarbon INFO @ 11:26:14] 0.029407 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:15] Energy consumed for RAM : 0.003014 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:15] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:15] Energy consumed for All CPU : 0.036451 kWh
[codecarbon INFO @ 11:26:15] 0.039465 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:15] Energy consumed for RAM : 0.001529 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:15] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:15] Energy consumed for All CPU : 0.018445 kWh
[codecarbon INFO @ 11:26:15] 0.019975 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:15] Energy consumed for RAM : 0.003351 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:15] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:15] Energy consumed for All CPU : 0.040434 kWh
[codecarbon INFO @ 11:26:15] 0.043785 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:15] Energy consumed for RAM : 0.002998 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:15] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:15] Energy consumed for All CPU : 0.036178 kWh
[codecarbon INFO @ 11:26:15] 0.039176 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:15] Energy consumed for RAM : 0.003271 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:15] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:15] Energy consumed for All CPU : 0.039556 kWh
[codecarbon INFO @ 11:26:15] 0.042827 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:15] 0.016242 g.CO2eq/s mean an estimation of 512.2187868836022 kg.CO2eq/year
[codecarbon INFO @ 11:26:15] Energy consumed for RAM : 0.000011 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:15] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:15] Energy consumed for All CPU : 0.000133 kWh
[codecarbon INFO @ 11:26:15] 0.000144 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:15] Energy consumed for RAM : 0.002258 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:15] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:15] Energy consumed for All CPU : 0.027185 kWh
[codecarbon INFO @ 11:26:15] 0.029443 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:16] Energy consumed for RAM : 0.003017 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:16] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:16] Energy consumed for All CPU : 0.036484 kWh
[codecarbon INFO @ 11:26:16] 0.039501 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:16] Energy consumed for RAM : 0.001532 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:16] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:16] Energy consumed for All CPU : 0.018478 kWh
[codecarbon INFO @ 11:26:16] 0.020011 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:16] Energy consumed for RAM : 0.003353 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:16] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:16] Energy consumed for All CPU : 0.040467 kWh
[codecarbon INFO @ 11:26:16] 0.043821 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:16] Energy consumed for RAM : 0.003001 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:16] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:16] Energy consumed for All CPU : 0.036212 kWh
[codecarbon INFO @ 11:26:16] 0.039213 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:16] Energy consumed for RAM : 0.003274 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:16] 0.016207 g.CO2eq/s mean an estimation of 511.1033816353803 kg.CO2eq/year
[codecarbon INFO @ 11:26:16] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:16] Energy consumed for All CPU : 0.039590 kWh
[codecarbon INFO @ 11:26:16] 0.042864 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:16] Energy consumed for RAM : 0.000014 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:16] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:16] Energy consumed for All CPU : 0.000166 kWh
[codecarbon INFO @ 11:26:16] 0.000180 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:16] Energy consumed for RAM : 0.002261 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:16] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:16] Energy consumed for All CPU : 0.027218 kWh
[codecarbon INFO @ 11:26:16] 0.029479 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:17] Energy consumed for RAM : 0.003020 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:17] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:17] Energy consumed for All CPU : 0.036517 kWh
[codecarbon INFO @ 11:26:17] 0.039537 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:17] Energy consumed for RAM : 0.001535 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:17] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:17] Energy consumed for All CPU : 0.018512 kWh
[codecarbon INFO @ 11:26:17] 0.020047 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:17] Energy consumed for RAM : 0.003356 kWh. RAM Power : 10.0 W

📏 Average review length: 822.63 characters

=== CodeCarbon Tracking Summary ===
Project: demo_experiment
Output CSV: /gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emissions_pandas.csv

Most frequent keywords

In [ ]:
from collections import Counter
import re

# Initialize the tracker with detailed logging
tracker = EmissionsTracker(
    project_name="demo_experiment",
    output_dir=log_dir,
    measure_power_secs=1,        # frequency of power measurement
    log_level="info",            # ensures detailed console + file logs
    save_to_file=True,           # ensure CSV file is written
)

# Start tracking
tracker.start()

# Simulate a computation workload
for _ in range(1000):
    a = np.random.rand(500, 500)
    b = np.random.rand(500, 500)
    np.dot(a, b)


# Fusionner tous les textes en une seule chaîne
all_text = " ".join(book_df['review/text'].dropna().astype(str))

# Nettoyer le texte : mettre en minuscule, retirer ponctuation
all_text = re.sub(r'[^\w\s]', '', all_text.lower())

# Créer une liste de mots
words = all_text.split()

# Compter la fréquence de chaque mot
word_counts = Counter(words)

# Top 20 mots les plus fréquents
most_common_words = word_counts.most_common(20)

print("Top 20 most frequent keywords:")
for word, count in most_common_words:
    print(f"{word}: {count}")

# Stop tracking
emissions = tracker.stop()

# Print summary
print("\n=== CodeCarbon Tracking Summary ===")
print(f"Project: {tracker._project_name}")
print(f"Output CSV: {os.path.join(log_dir, 'emissions_pandas.csv')}")

[codecarbon INFO @ 11:26:49] Energy consumed for RAM : 0.003114 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:49] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:49] Energy consumed for All CPU : 0.037584 kWh
[codecarbon INFO @ 11:26:49] 0.040698 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:49] Energy consumed for RAM : 0.003366 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:49] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:49] Energy consumed for All CPU : 0.040815 kWh
[codecarbon WARNING @ 11:26:49] Multiple instances of codecarbon are allowed to run at the same time.
[codecarbon INFO @ 11:26:49] Energy consumed for RAM : 0.003090 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:49] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:49] Energy consumed for All CPU : 0.037295 kWh
[codecarbon INFO @ 11:26:49] 0.044181 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:49] 0.040385 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:49] 0.016229 g.CO2eq/s mean an estimation of 511.79591706524695 kg.CO2eq/year
[codecarbon INFO @ 11:26:49] [setup] RAM Tracking...
[codecarbon INFO @ 11:26:49] [setup] CPU Tracking...
[codecarbon INFO @ 11:26:49] Energy consumed for RAM : 0.001630 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:49] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:49] Energy consumed for All CPU : 0.019703 kWh
[codecarbon INFO @ 11:26:49] 0.021332 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:50] Energy consumed for RAM : 0.002353 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:50] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:50] Energy consumed for All CPU : 0.028332 kWh
[codecarbon INFO @ 11:26:50] 0.030685 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:50] Energy consumed for RAM : 0.003449 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:50] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:50] Energy consumed for All CPU : 0.041586 kWh
[codecarbon INFO @ 11:26:50] 0.045035 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:50] 0.016241 g.CO2eq/s mean an estimation of 512.1785560765657 kg.CO2eq/year
[codecarbon INFO @ 11:26:50] Energy consumed for RAM : 0.003117 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:50] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:50] Energy consumed for All CPU : 0.037618 kWh
[codecarbon INFO @ 11:26:50] 0.040734 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:50] Energy consumed for RAM : 0.003369 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:50] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:50] Energy consumed for RAM : 0.003092 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:50] Energy consumed for All CPU : 0.040848 kWh
[codecarbon INFO @ 11:26:50] 0.044217 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:50] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:50] Energy consumed for All CPU : 0.037328 kWh
[codecarbon INFO @ 11:26:50] 0.040421 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:50] Energy consumed for RAM : 0.001632 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:50] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:50] Energy consumed for All CPU : 0.019736 kWh
[codecarbon INFO @ 11:26:50] 0.021368 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon WARNING @ 11:26:51] No CPU tracking mode found. Falling back on estimation based on TDP for CPU.
 Linux OS detected: Please ensure RAPL files exist at /sys/class/powercap/intel-rapl/subsystem to measure CPU

[codecarbon INFO @ 11:26:51] CPU Model on constant consumption mode: AMD EPYC 7B12
[codecarbon WARNING @ 11:26:51] No CPU tracking mode found. Falling back on CPU constant mode.
[codecarbon INFO @ 11:26:51] [setup] GPU Tracking...
[codecarbon INFO @ 11:26:51] No GPU found.
[codecarbon INFO @ 11:26:51] The below tracking methods have been set up:
                RAM Tracking Method: RAM power estimation model
                CPU Tracking Method: global constant
                GPU Tracking Method: Unspecified

[codecarbon INFO @ 11:26:51] >>> Tracker's metadata:
[codecarbon INFO @ 11:26:51]   Platform system: Linux-6.6.105+-x86_64-with-glibc2.35
[codecarbon INFO @ 11:26:51]   Python version: 3.12.12
[codecarbon INFO @ 11:26:51]   CodeCarbon version: 3.0.8
[codecarbon INFO @ 11:26:51]   Available RAM : 12.671 GB
[codecarbon INFO @ 11:26:51]   CPU count: 2 thread(s) in 1 physical CPU(s)
[codecarbon INFO @ 11:26:51]   CPU model: AMD EPYC 7B12
[codecarbon INFO @ 11:26:51]   GPU count: None
[codecarbon INFO @ 11:26:51]   GPU model: None
[codecarbon INFO @ 11:26:51] Emissions data (if any) will be saved to file /gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emissions.csv
[codecarbon INFO @ 11:26:51] Energy consumed for RAM : 0.002356 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:51] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:51] Energy consumed for All CPU : 0.028365 kWh
[codecarbon INFO @ 11:26:51] 0.030721 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:51] Energy consumed for RAM : 0.003452 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:51] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:51] Energy consumed for All CPU : 0.041619 kWh
[codecarbon INFO @ 11:26:51] 0.045071 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:51] Energy consumed for RAM : 0.003119 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:51] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:51] Energy consumed for All CPU : 0.037651 kWh
[codecarbon INFO @ 11:26:51] 0.040770 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:51] Energy consumed for RAM : 0.003372 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:51] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:51] Energy consumed for All CPU : 0.040881 kWh
[codecarbon INFO @ 11:26:51] 0.044253 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:51] Energy consumed for RAM : 0.003095 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:51] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:51] Energy consumed for All CPU : 0.037362 kWh
[codecarbon INFO @ 11:26:51] 0.040457 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:51] 0.016240 g.CO2eq/s mean an estimation of 512.1373975014307 kg.CO2eq/year
[codecarbon INFO @ 11:26:51] Energy consumed for RAM : 0.001635 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:51] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:51] Energy consumed for All CPU : 0.019769 kWh
[codecarbon INFO @ 11:26:51] 0.021404 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:52] Energy consumed for RAM : 0.000003 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:52] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:52] Energy consumed for All CPU : 0.000034 kWh
[codecarbon INFO @ 11:26:52] 0.000036 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:52] Energy consumed for RAM : 0.002359 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:52] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:52] Energy consumed for All CPU : 0.028399 kWh
[codecarbon INFO @ 11:26:52] 0.030757 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:52] Energy consumed for RAM : 0.003455 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:52] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:52] Energy consumed for All CPU : 0.041652 kWh
[codecarbon INFO @ 11:26:52] 0.045107 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:52] Energy consumed for RAM : 0.003122 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:52] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:52] Energy consumed for RAM : 0.003374 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:52] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:52] Energy consumed for All CPU : 0.040915 kWh
[codecarbon INFO @ 11:26:52] 0.044289 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:52] Energy consumed for All CPU : 0.037684 kWh
[codecarbon INFO @ 11:26:52] 0.040806 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:52] Energy consumed for RAM : 0.003098 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:52] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:52] Energy consumed for All CPU : 0.037395 kWh
[codecarbon INFO @ 11:26:52] 0.040493 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:52] Energy consumed for RAM : 0.001638 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:52] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:52] Energy consumed for All CPU : 0.019802 kWh
[codecarbon INFO @ 11:26:52] 0.021440 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:53] Energy consumed for RAM : 0.000006 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:53] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:53] Energy consumed for All CPU : 0.000067 kWh
[codecarbon INFO @ 11:26:53] 0.000072 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:53] Energy consumed for RAM : 0.002361 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:53] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:53] Energy consumed for All CPU : 0.028432 kWh
[codecarbon INFO @ 11:26:53] 0.030793 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:53] Energy consumed for RAM : 0.003458 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:53] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:53] Energy consumed for All CPU : 0.041686 kWh
[codecarbon INFO @ 11:26:53] 0.045144 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:53] Energy consumed for RAM : 0.003125 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:53] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:53] Energy consumed for All CPU : 0.037717 kWh
[codecarbon INFO @ 11:26:53] Energy consumed for RAM : 0.003377 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:53] 0.040842 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:53] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:53] Energy consumed for All CPU : 0.040948 kWh
[codecarbon INFO @ 11:26:53] 0.044325 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:53] Energy consumed for RAM : 0.003101 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:53] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:53] Energy consumed for All CPU : 0.037428 kWh
[codecarbon INFO @ 11:26:53] 0.040529 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:53] Energy consumed for RAM : 0.001641 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:53] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:53] Energy consumed for All CPU : 0.019835 kWh
[codecarbon INFO @ 11:26:53] 0.021476 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:53] 0.016247 g.CO2eq/s mean an estimation of 512.3799203391734 kg.CO2eq/year
[codecarbon INFO @ 11:26:54] Energy consumed for RAM : 0.000008 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:54] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:54] Energy consumed for All CPU : 0.000100 kWh
[codecarbon INFO @ 11:26:54] 0.000108 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:54] Energy consumed for RAM : 0.002364 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:54] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:54] Energy consumed for All CPU : 0.028465 kWh
[codecarbon INFO @ 11:26:54] 0.030829 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:54] Energy consumed for RAM : 0.003460 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:54] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:54] Energy consumed for All CPU : 0.041719 kWh
[codecarbon INFO @ 11:26:54] 0.045180 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:54] Energy consumed for RAM : 0.003128 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:54] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:54] Energy consumed for All CPU : 0.037750 kWh
[codecarbon INFO @ 11:26:54] 0.040878 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:54] Energy consumed for RAM : 0.003380 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:54] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:54] Energy consumed for All CPU : 0.040981 kWh
[codecarbon INFO @ 11:26:54] 0.016215 g.CO2eq/s mean an estimation of 511.34090826856334 kg.CO2eq/year
[codecarbon INFO @ 11:26:54] Energy consumed for RAM : 0.003103 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:54] 0.044361 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:54] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:54] Energy consumed for All CPU : 0.037461 kWh
[codecarbon INFO @ 11:26:54] 0.040565 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:54] Energy consumed for RAM : 0.001643 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:54] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:54] Energy consumed for All CPU : 0.019868 kWh
[codecarbon INFO @ 11:26:54] 0.021512 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:55] Energy consumed for RAM : 0.000011 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:55] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:55] Energy consumed for All CPU : 0.000133 kWh
[codecarbon INFO @ 11:26:55] 0.000144 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:55] Energy consumed for RAM : 0.002367 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:55] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:55] Energy consumed for All CPU : 0.028498 kWh
[codecarbon INFO @ 11:26:55] 0.030865 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:55] Energy consumed for RAM : 0.003463 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:55] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:55] Energy consumed for All CPU : 0.041752 kWh
[codecarbon INFO @ 11:26:55] 0.045215 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:55] Energy consumed for RAM : 0.003130 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:55] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:55] Energy consumed for RAM : 0.003383 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:55] Delta energy consumed for CPU with constant : 0.000032 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:55] Energy consumed for All CPU : 0.041014 kWh
[codecarbon INFO @ 11:26:55] 0.044396 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:55] Energy consumed for All CPU : 0.037783 kWh
[codecarbon INFO @ 11:26:55] 0.040913 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:55] Energy consumed for RAM : 0.003106 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:55] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:55] Energy consumed for All CPU : 0.037494 kWh
[codecarbon INFO @ 11:26:55] 0.040600 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:55] Energy consumed for RAM : 0.001646 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:55] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:55] Energy consumed for All CPU : 0.019901 kWh
[codecarbon INFO @ 11:26:55] 0.021547 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:56] Energy consumed for RAM : 0.000014 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:56] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:56] Energy consumed for All CPU : 0.000166 kWh
[codecarbon INFO @ 11:26:56] 0.000180 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:56] Energy consumed for RAM : 0.002370 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:56] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:56] Energy consumed for All CPU : 0.028531 kWh
[codecarbon INFO @ 11:26:56] Energy consumed for RAM : 0.003466 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:26:56] 0.030901 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:26:56] 0.016232 g.CO2eq/s mean an estimation of 511.90108516700803 kg.CO2eq/year
[codecarbon INFO @ 11:26:56] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 11:26:56] Energy consumed for All CPU : 0.041785 kWh
[codecarbon INFO @ 11:26:56] 0.045251 kWh of electricity and 0.000000 L of water were used since the beginning.

In [ ]:
# Install dependencies first:
#pip install codecarbon numpy

from codecarbon import EmissionsTracker
import numpy as np
import os

# Optional: define an output directory for logs
log_dir = "./carbon_logs"
os.makedirs(log_dir, exist_ok=True)

# Initialize the tracker with detailed logging
tracker = EmissionsTracker(
    project_name="demo_experiment",
    output_dir=log_dir,
    measure_power_secs=1,        # frequency of power measurement
    log_level="info",            # ensures detailed console + file logs
    save_to_file=True,           # ensure CSV file is written
)

# Start tracking
tracker.start()

# Simulate a computation workload
for _ in range(1000):
    a = np.random.rand(500, 500)
    b = np.random.rand(500, 500)
    np.dot(a, b)

# Stop tracking
emissions = tracker.stop()

# Print summary
print("\n=== CodeCarbon Tracking Summary ===")
print(f"Project: {tracker._project_name}")
print(f"Output CSV: {os.path.join(log_dir, 'emissions_pandas.csv')}")

In [ ]:

# Initialize the tracker with detailed logging
tracker = EmissionsTracker(
    project_name="demo_experiment",
    output_dir=log_dir,
    measure_power_secs=1,        # frequency of power measurement
    log_level="info",            # ensures detailed console + file logs
    save_to_file=True,           # ensure CSV file is written
)

# Start tracking
tracker.start()

# Simulate a computation workload
for _ in range(1000):
    a = np.random.rand(500, 500)
    b = np.random.rand(500, 500)
    np.dot(a, b)

book_df.to_csv("book.csv", index=False, sep=";")

# Stop tracking
emissions = tracker.stop()

# Print summary
print("\n=== CodeCarbon Tracking Summary ===")
print(f"Project: {tracker._project_name}")
print(f"Output CSV: {os.path.join(log_dir, 'emissions_pandas.csv')}")

[codecarbon WARNING @ 12:53:21] Multiple instances of codecarbon are allowed to run at the same time.
[codecarbon INFO @ 12:53:21] [setup] RAM Tracking...
[codecarbon INFO @ 12:53:21] [setup] CPU Tracking...
[codecarbon WARNING @ 12:53:22] No CPU tracking mode found. Falling back on estimation based on TDP for CPU.
 Linux OS detected: Please ensure RAPL files exist at /sys/class/powercap/intel-rapl/subsystem to measure CPU

[codecarbon INFO @ 12:53:22] CPU Model on constant consumption mode: AMD EPYC 7B12
[codecarbon WARNING @ 12:53:22] No CPU tracking mode found. Falling back on CPU constant mode.
[codecarbon INFO @ 12:53:22] [setup] GPU Tracking...
[codecarbon INFO @ 12:53:22] No GPU found.
[codecarbon INFO @ 12:53:22] The below tracking methods have been set up:
                RAM Tracking Method: RAM power estimation model
                CPU Tracking Method: global constant
                GPU Tracking Method: Unspecified

[codecarbon INFO @ 12:53:22] >>> Tracker's metadata:
[codecarbon INFO @ 12:53:22]   Platform system: Linux-6.6.105+-x86_64-with-glibc2.35
[codecarbon INFO @ 12:53:22]   Python version: 3.12.12
[codecarbon INFO @ 12:53:22]   CodeCarbon version: 3.0.8
[codecarbon INFO @ 12:53:22]   Available RAM : 12.671 GB
[codecarbon INFO @ 12:53:22]   CPU count: 2 thread(s) in 1 physical CPU(s)
[codecarbon INFO @ 12:53:22]   CPU model: AMD EPYC 7B12
[codecarbon INFO @ 12:53:22]   GPU count: None
[codecarbon INFO @ 12:53:22]   GPU model: None
[codecarbon INFO @ 12:53:22] Emissions data (if any) will be saved to file /gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emissions.csv
[codecarbon INFO @ 12:53:23] Energy consumed for RAM : 0.000003 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:23] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:23] Energy consumed for All CPU : 0.000034 kWh
[codecarbon INFO @ 12:53:23] 0.000036 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:24] Energy consumed for RAM : 0.000006 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:24] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:24] Energy consumed for All CPU : 0.000067 kWh
[codecarbon INFO @ 12:53:24] 0.000072 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:25] Energy consumed for RAM : 0.000008 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:25] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:25] Energy consumed for All CPU : 0.000100 kWh
[codecarbon INFO @ 12:53:25] 0.000108 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:26] Energy consumed for RAM : 0.000011 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:26] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:26] Energy consumed for All CPU : 0.000133 kWh
[codecarbon INFO @ 12:53:26] 0.000144 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:27] Energy consumed for RAM : 0.000014 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:27] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:27] Energy consumed for All CPU : 0.000167 kWh
[codecarbon INFO @ 12:53:27] 0.000180 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:28] Energy consumed for RAM : 0.000017 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:28] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:28] Energy consumed for All CPU : 0.000200 kWh
[codecarbon INFO @ 12:53:28] 0.000216 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:29] Energy consumed for RAM : 0.000019 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:29] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:29] Energy consumed for All CPU : 0.000233 kWh
[codecarbon INFO @ 12:53:29] 0.000252 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:30] Energy consumed for RAM : 0.000022 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:30] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:30] Energy consumed for All CPU : 0.000266 kWh
[codecarbon INFO @ 12:53:30] 0.000288 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:30] 0.016195 g.CO2eq/s mean an estimation of 510.71567396727824 kg.CO2eq/year
[codecarbon INFO @ 12:53:31] Energy consumed for RAM : 0.000025 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:31] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:31] Energy consumed for All CPU : 0.000299 kWh
[codecarbon INFO @ 12:53:31] 0.000323 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:32] Energy consumed for RAM : 0.000027 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:32] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:32] Energy consumed for All CPU : 0.000331 kWh
[codecarbon INFO @ 12:53:32] 0.000359 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:33] Energy consumed for RAM : 0.000030 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:33] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:33] Energy consumed for All CPU : 0.000364 kWh
[codecarbon INFO @ 12:53:33] 0.000394 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:34] Energy consumed for RAM : 0.000033 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:34] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:34] Energy consumed for All CPU : 0.000397 kWh
[codecarbon INFO @ 12:53:34] 0.000430 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:35] Energy consumed for RAM : 0.000036 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:35] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:35] Energy consumed for All CPU : 0.000431 kWh
[codecarbon INFO @ 12:53:35] 0.000466 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:36] Energy consumed for RAM : 0.000038 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:36] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:36] Energy consumed for All CPU : 0.000464 kWh
[codecarbon INFO @ 12:53:36] 0.000502 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:37] Energy consumed for RAM : 0.000041 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:37] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:37] Energy consumed for All CPU : 0.000497 kWh
[codecarbon INFO @ 12:53:37] 0.000538 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:38] Energy consumed for RAM : 0.000044 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:38] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:38] Energy consumed for All CPU : 0.000530 kWh
[codecarbon INFO @ 12:53:38] 0.000574 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:38] 0.016213 g.CO2eq/s mean an estimation of 511.2804558027658 kg.CO2eq/year
[codecarbon INFO @ 12:53:39] Energy consumed for RAM : 0.000047 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:39] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:39] Energy consumed for All CPU : 0.000564 kWh
[codecarbon INFO @ 12:53:39] 0.000610 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:40] Energy consumed for RAM : 0.000050 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:40] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:40] Energy consumed for All CPU : 0.000597 kWh
[codecarbon INFO @ 12:53:40] 0.000646 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:41] Energy consumed for RAM : 0.000052 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:41] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:41] Energy consumed for All CPU : 0.000630 kWh
[codecarbon INFO @ 12:53:41] 0.000682 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:42] Energy consumed for RAM : 0.000055 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:42] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:42] Energy consumed for All CPU : 0.000663 kWh
[codecarbon INFO @ 12:53:42] 0.000718 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:43] Energy consumed for RAM : 0.000058 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:43] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:43] Energy consumed for All CPU : 0.000696 kWh
[codecarbon INFO @ 12:53:43] 0.000754 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:44] Energy consumed for RAM : 0.000060 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:44] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:44] Energy consumed for All CPU : 0.000729 kWh
[codecarbon INFO @ 12:53:44] 0.000789 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:45] Energy consumed for RAM : 0.000063 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:45] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:45] Energy consumed for All CPU : 0.000762 kWh
[codecarbon INFO @ 12:53:45] 0.000825 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:46] Energy consumed for RAM : 0.000066 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:46] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:46] Energy consumed for All CPU : 0.000795 kWh
[codecarbon INFO @ 12:53:46] 0.000861 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:46] 0.016192 g.CO2eq/s mean an estimation of 510.6388211830595 kg.CO2eq/year
[codecarbon INFO @ 12:53:47] Energy consumed for RAM : 0.000069 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:47] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:47] Energy consumed for All CPU : 0.000829 kWh
[codecarbon INFO @ 12:53:47] 0.000898 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:48] Energy consumed for RAM : 0.000071 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:48] Delta energy consumed for CPU with constant : 0.000032 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:48] Energy consumed for All CPU : 0.000861 kWh
[codecarbon INFO @ 12:53:48] 0.000933 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:49] Energy consumed for RAM : 0.000074 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:49] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:49] Energy consumed for All CPU : 0.000895 kWh
[codecarbon INFO @ 12:53:49] 0.000969 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:50] Energy consumed for RAM : 0.000077 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:50] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:50] Energy consumed for All CPU : 0.000928 kWh
[codecarbon INFO @ 12:53:50] 0.001005 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:51] Energy consumed for RAM : 0.000080 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:51] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:51] Energy consumed for All CPU : 0.000961 kWh
[codecarbon INFO @ 12:53:51] 0.001041 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:52] Energy consumed for RAM : 0.000082 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:52] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:52] Energy consumed for All CPU : 0.000994 kWh
[codecarbon INFO @ 12:53:52] 0.001076 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:53] Energy consumed for RAM : 0.000085 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:53] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:53] Energy consumed for All CPU : 0.001028 kWh
[codecarbon INFO @ 12:53:53] 0.001113 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:54] Energy consumed for RAM : 0.000088 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:54] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:54] Energy consumed for All CPU : 0.001061 kWh
[codecarbon INFO @ 12:53:54] 0.001149 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:54] 0.016236 g.CO2eq/s mean an estimation of 512.0068019466445 kg.CO2eq/year
[codecarbon INFO @ 12:53:55] Energy consumed for RAM : 0.000091 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:55] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:55] Energy consumed for All CPU : 0.001094 kWh
[codecarbon INFO @ 12:53:55] 0.001185 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:56] Energy consumed for RAM : 0.000093 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:56] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:56] Energy consumed for All CPU : 0.001127 kWh
[codecarbon INFO @ 12:53:56] 0.001221 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:57] Energy consumed for RAM : 0.000096 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:57] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:57] Energy consumed for All CPU : 0.001160 kWh
[codecarbon INFO @ 12:53:57] 0.001256 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:58] Energy consumed for RAM : 0.000099 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:58] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:58] Energy consumed for All CPU : 0.001193 kWh
[codecarbon INFO @ 12:53:58] 0.001292 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:53:59] Energy consumed for RAM : 0.000102 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:53:59] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:53:59] Energy consumed for All CPU : 0.001226 kWh
[codecarbon INFO @ 12:53:59] 0.001328 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:54:00] Energy consumed for RAM : 0.000104 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:54:00] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:54:00] Energy consumed for All CPU : 0.001259 kWh
[codecarbon INFO @ 12:54:00] 0.001364 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:54:01] Energy consumed for RAM : 0.000107 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:54:01] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:54:01] Energy consumed for All CPU : 0.001292 kWh
[codecarbon INFO @ 12:54:01] 0.001399 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:54:02] Energy consumed for RAM : 0.000110 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:54:02] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:54:02] Energy consumed for All CPU : 0.001325 kWh
[codecarbon INFO @ 12:54:02] 0.001435 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:54:02] 0.016183 g.CO2eq/s mean an estimation of 510.33176765788926 kg.CO2eq/year
[codecarbon INFO @ 12:54:03] Energy consumed for RAM : 0.000113 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:54:03] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:54:03] Energy consumed for All CPU : 0.001359 kWh
[codecarbon INFO @ 12:54:03] 0.001472 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:54:04] Energy consumed for RAM : 0.000115 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:54:04] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:54:04] Energy consumed for All CPU : 0.001392 kWh
[codecarbon INFO @ 12:54:04] 0.001507 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:54:05] Energy consumed for RAM : 0.000118 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:54:05] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:54:05] Energy consumed for All CPU : 0.001425 kWh
[codecarbon INFO @ 12:54:05] 0.001543 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:54:06] Energy consumed for RAM : 0.000121 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:54:06] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:54:06] Energy consumed for All CPU : 0.001458 kWh
[codecarbon INFO @ 12:54:06] 0.001579 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:54:07] Energy consumed for RAM : 0.000124 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:54:07] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:54:07] Energy consumed for All CPU : 0.001491 kWh
[codecarbon INFO @ 12:54:07] 0.001615 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:54:08] Energy consumed for RAM : 0.000126 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:54:08] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:54:08] Energy consumed for All CPU : 0.001524 kWh
[codecarbon INFO @ 12:54:08] 0.001651 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:54:09] Energy consumed for RAM : 0.000129 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 12:54:09] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 12:54:09] Energy consumed for All CPU : 0.001557 kWh
[codecarbon INFO @ 12:54:09] 0.001686 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 12:54:10] Energy consumed for RAM : 0.000132 kWh. RAM Power : 10.0 W

=== CodeCarbon Tracking Summary ===
Project: demo_experiment
Output CSV: /gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emissions_pandas.csv

Parquet

In [ ]:
'G:\\Mon Drive\\TP2_Green_IT\\Data\\archive.zip'
from google.colab import drive
drive.mount('/gdrive')
!ls '/gdrive'
fichier_archive = 'gdrive/MyDrive/TP2_Green_IT/Data/archive.zip'

#@title
!unzip '/gdrive/MyDrive/TP2_Green_IT/Data/archive.zip'

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
MyDrive
Archive:  /gdrive/MyDrive/TP2_Green_IT/Data/archive.zip
replace Books_rating.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace books_data.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n

In [ ]:
import pandas as pd
books_rating = pd.read_csv("Books_rating.csv")
books_data = pd.read_csv("books_data.csv")
books_rating.to_parquet("books.parquet", compression="snappy", index=False)
books_data.to_parquet("reviews.parquet", compression="snappy", index=False)

In [ ]:
books_rating_df = pd.read_parquet("books.parquet")
books_rating_df.head()

,Id,Title,Price,User_id,profileName,review/helpfulness,review/score,review/time,review/summary,review/text
0,1882931173,Its Only Art If Its Well Hung!,NaN,AVCGYZL8FQQTD,"Jim of Oz ""jim-of-oz""",7/7,4.0,940636800,Nice collection of Julie Strain images,This is only for Julie Strain fans. It's a col...
1,0826414346,Dr. Seuss: American Icon,NaN,A30TK6U7DNS82R,Kevin Killian,10/10,5.0,1095724800,Really Enjoyed It,I don't care much for Dr. Seuss but after read...
2,0826414346,Dr. Seuss: American Icon,NaN,A3UH4UZ4RSVO82,John Granger,10/11,5.0,1078790400,Essential for every personal and Public Library,"If people become the books they read and if ""t..."
3,0826414346,Dr. Seuss: American Icon,NaN,A2MVUWT453QH61,"Roy E. Perry ""amateur philosopher""",7/7,4.0,1090713600,Phlip Nel gives silly Seuss a serious treatment,"Theodore Seuss Geisel (1904-1991), aka &quot;D..."
4,0826414346,Dr. Seuss: American Icon,NaN,A22X4XUPKF66MR,"D. H. Richards ""ninthwavestore""",3/3,4.0,1107993600,Good academic overview,Philip Nel - Dr. Seuss: American IconThis is b...

In [ ]:
books_data_df= pd.read_parquet("reviews.parquet")
books_data_df.head()

,Title,description,authors,image,previewLink,publisher,publishedDate,infoLink,categories,ratingsCount
0,Its Only Art If Its Well Hung!,None,['Julie Strain'],http://books.google.com/books/content?id=DykPA...,http://books.google.nl/books?id=DykPAAAACAAJ&d...,None,1996,http://books.google.nl/books?id=DykPAAAACAAJ&d...,['Comics & Graphic Novels'],NaN
1,Dr. Seuss: American Icon,Philip Nel takes a fascinating look into the k...,['Philip Nel'],http://books.google.com/books/content?id=IjvHQ...,http://books.google.nl/books?id=IjvHQsCn_pgC&p...,A&C Black,2005-01-01,http://books.google.nl/books?id=IjvHQsCn_pgC&d...,['Biography & Autobiography'],NaN
2,Wonderful Worship in Smaller Churches,This resource includes twelve principles in un...,['David R. Ray'],http://books.google.com/books/content?id=2tsDA...,http://books.google.nl/books?id=2tsDAAAACAAJ&d...,None,2000,http://books.google.nl/books?id=2tsDAAAACAAJ&d...,['Religion'],NaN
3,Whispers of the Wicked Saints,Julia Thomas finds her life spinning out of co...,['Veronica Haddon'],http://books.google.com/books/content?id=aRSIg...,http://books.google.nl/books?id=aRSIgJlq6JwC&d...,iUniverse,2005-02,http://books.google.nl/books?id=aRSIgJlq6JwC&d...,['Fiction'],NaN
4,"Nation Dance: Religion, Identity and Cultural ...",None,['Edward Long'],None,http://books.google.nl/books?id=399SPgAACAAJ&d...,None,2003-03-01,http://books.google.nl/books?id=399SPgAACAAJ&d...,None,NaN

In [ ]:
import ast
books_data_df = pd.read_parquet("reviews.parquet")

# Sélection des colonnes importantes
sbooks_data_df = books_data_df[['Title', 'authors', 'publisher', 'categories', 'ratingsCount']].copy()

#Remplissage des valeurs manquantes
sbooks_data_df.fillna({
    'ratingsCount': 0,
    'Title': 'Unknown',
    'authors': 'Unknown',
    'publisher': 'Unknown',
    'categories': 'Unknown'
}, inplace=True)

# Vérification des valeurs manquantes
display(sbooks_data_df.isnull().sum())

# Affichage rapide pour contrôle
display(sbooks_data_df[['Title', 'authors', 'categories']].head())

# Fonction pour convertir les chaînes de type liste en liste Python
def safe_literal_eval(x):
    try:
        return ast.literal_eval(x)
    except (ValueError, SyntaxError):
        return []

# Normalisation des colonnes 'authors' et 'categories'
sbooks_data_df['authors'] = sbooks_data_df['authors'].apply(safe_literal_eval)
sbooks_data_df['categories'] = sbooks_data_df['categories'].apply(safe_literal_eval)

print("Normalized 'authors' and 'categories' columns in sbooks_data_df:")
display(sbooks_data_df[['Title', 'authors', 'categories']].head())

# Enregistrement du DataFrame nettoyé directement en Parquet
sbooks_data_df.to_parquet("sbooks_data.parquet", compression="snappy", index=False)

Title           0
authors         0
publisher       0
categories      0
ratingsCount    0
dtype: int64

,Title,authors,categories
0,Its Only Art If Its Well Hung!,['Julie Strain'],['Comics & Graphic Novels']
1,Dr. Seuss: American Icon,['Philip Nel'],['Biography & Autobiography']
2,Wonderful Worship in Smaller Churches,['David R. Ray'],['Religion']
3,Whispers of the Wicked Saints,['Veronica Haddon'],['Fiction']
4,"Nation Dance: Religion, Identity and Cultural ...",['Edward Long'],Unknown

Normalized 'authors' and 'categories' columns in sbooks_data_df:

,Title,authors,categories
0,Its Only Art If Its Well Hung!,[Julie Strain],[Comics & Graphic Novels]
1,Dr. Seuss: American Icon,[Philip Nel],[Biography & Autobiography]
2,Wonderful Worship in Smaller Churches,[David R. Ray],[Religion]
3,Whispers of the Wicked Saints,[Veronica Haddon],[Fiction]
4,"Nation Dance: Religion, Identity and Cultural ...",[Edward Long],[]

In [ ]:
books_rating_df = pd.read_parquet("books.parquet")
sbooks_rating_df = books_rating_df[['Title', 'review/score', 'review/text']].copy()
sbooks_rating_df.fillna({
    'review/score': 0,
    'Title': 'Unknown',
    'review/text': 'Unknown'
}, inplace=True)

display(sbooks_rating_df.isnull().sum())

display(sbooks_rating_df.head())

Title           0
review/score    0
review/text     0
dtype: int64

,Title,review/score,review/text
0,Its Only Art If Its Well Hung!,4.0,This is only for Julie Strain fans. It's a col...
1,Dr. Seuss: American Icon,5.0,I don't care much for Dr. Seuss but after read...
2,Dr. Seuss: American Icon,5.0,"If people become the books they read and if ""t..."
3,Dr. Seuss: American Icon,4.0,"Theodore Seuss Geisel (1904-1991), aka &quot;D..."
4,Dr. Seuss: American Icon,4.0,Philip Nel - Dr. Seuss: American IconThis is b...

In [ ]:
import codecarbon
from codecarbon import EmissionsTracker
import numpy as np
import os
import pandas as pd

# Optional: define an output directory for logs
log_dir = "/gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3"
os.makedirs(log_dir, exist_ok=True)

In [ ]:
# Initialize the tracker with detailed logging
tracker = EmissionsTracker(
    project_name="demo_experiment",
    output_dir=log_dir,
    measure_power_secs=1,        # frequency of power measurement
    log_level="info",            # ensures detailed console + file logs
    save_to_file=True,           # ensure CSV file is written
)

# Start tracking
tracker.start()


sbooks_data_df = pd.read_parquet("reviews.parquet")
sbooks_rating_df = pd.read_parquet("books.parquet")

book_df = pd.merge(
    sbooks_data_df,
    sbooks_rating_df,
    on='Title',
    how='inner'  # options: 'inner', 'left', 'right', 'outer'
)

# Stop tracking
emissions = tracker.stop()

# Print summary
print("\n=== CodeCarbon Tracking Summary ===")
print(f"Project: {tracker._project_name}")
print(f"Output CSV: {os.path.join(log_dir, 'emissions_parquet.csv')}")

[codecarbon WARNING @ 14:00:04] Multiple instances of codecarbon are allowed to run at the same time.
[codecarbon INFO @ 14:00:04] [setup] RAM Tracking...
[codecarbon INFO @ 14:00:04] [setup] CPU Tracking...
[codecarbon WARNING @ 14:00:05] No CPU tracking mode found. Falling back on estimation based on TDP for CPU.
 Linux OS detected: Please ensure RAPL files exist at /sys/class/powercap/intel-rapl/subsystem to measure CPU

[codecarbon INFO @ 14:00:05] CPU Model on constant consumption mode: AMD EPYC 7B12
[codecarbon WARNING @ 14:00:05] No CPU tracking mode found. Falling back on CPU constant mode.
[codecarbon INFO @ 14:00:05] [setup] GPU Tracking...
[codecarbon INFO @ 14:00:05] No GPU found.
[codecarbon INFO @ 14:00:05] The below tracking methods have been set up:
                RAM Tracking Method: RAM power estimation model
                CPU Tracking Method: global constant
                GPU Tracking Method: Unspecified

[codecarbon INFO @ 14:00:05] >>> Tracker's metadata:
[codecarbon INFO @ 14:00:05]   Platform system: Linux-6.6.105+-x86_64-with-glibc2.35
[codecarbon INFO @ 14:00:05]   Python version: 3.12.12
[codecarbon INFO @ 14:00:05]   CodeCarbon version: 3.0.8
[codecarbon INFO @ 14:00:05]   Available RAM : 12.671 GB
[codecarbon INFO @ 14:00:05]   CPU count: 2 thread(s) in 1 physical CPU(s)
[codecarbon INFO @ 14:00:05]   CPU model: AMD EPYC 7B12
[codecarbon INFO @ 14:00:05]   GPU count: None
[codecarbon INFO @ 14:00:05]   GPU model: None
[codecarbon INFO @ 14:00:05] Emissions data (if any) will be saved to file /gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emissions.csv
[codecarbon INFO @ 14:00:06] Energy consumed for RAM : 0.000003 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:00:06] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 14:00:06] Energy consumed for All CPU : 0.000034 kWh
[codecarbon INFO @ 14:00:06] 0.000037 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:00:07] Energy consumed for RAM : 0.000006 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:00:08] Delta energy consumed for CPU with constant : 0.000049 kWh, power : 120.0 W
[codecarbon INFO @ 14:00:08] Energy consumed for All CPU : 0.000083 kWh
[codecarbon INFO @ 14:00:08] 0.000088 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:00:08] Energy consumed for RAM : 0.000007 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:00:08] Delta energy consumed for CPU with constant : 0.000018 kWh, power : 120.0 W
[codecarbon INFO @ 14:00:08] Energy consumed for All CPU : 0.000101 kWh
[codecarbon INFO @ 14:00:08] 0.000108 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:00:09] Energy consumed for RAM : 0.000010 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:00:09] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:00:09] Energy consumed for All CPU : 0.000134 kWh
[codecarbon INFO @ 14:00:09] 0.000144 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:00:10] Energy consumed for RAM : 0.000013 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:00:10] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:00:10] Energy consumed for All CPU : 0.000168 kWh
[codecarbon INFO @ 14:00:10] 0.000180 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:00:11] Energy consumed for RAM : 0.000015 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:00:11] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:00:11] Energy consumed for All CPU : 0.000201 kWh
[codecarbon INFO @ 14:00:11] 0.000216 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:00:12] Energy consumed for RAM : 0.000018 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:00:12] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:00:12] Energy consumed for All CPU : 0.000234 kWh
[codecarbon INFO @ 14:00:12] 0.000252 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:00:13] Energy consumed for RAM : 0.000021 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:00:13] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:00:13] Energy consumed for All CPU : 0.000267 kWh
[codecarbon INFO @ 14:00:13] 0.000288 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:00:14] 0.016174 g.CO2eq/s mean an estimation of 510.07004274564156 kg.CO2eq/year
[codecarbon INFO @ 14:00:14] Energy consumed for RAM : 0.000024 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:00:14] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:00:14] Energy consumed for All CPU : 0.000300 kWh
[codecarbon INFO @ 14:00:14] 0.000324 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:00:15] Energy consumed for RAM : 0.000027 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:00:15] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:00:15] Energy consumed for All CPU : 0.000334 kWh
[codecarbon INFO @ 14:00:15] 0.000360 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:00:16] Energy consumed for RAM : 0.000029 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:00:16] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:00:16] Energy consumed for All CPU : 0.000367 kWh
[codecarbon INFO @ 14:00:16] 0.000396 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:00:17] Energy consumed for RAM : 0.000032 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:00:17] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:00:17] Energy consumed for All CPU : 0.000400 kWh
[codecarbon INFO @ 14:00:17] 0.000432 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:00:18] Energy consumed for RAM : 0.000035 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:00:18] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:00:18] Energy consumed for All CPU : 0.000433 kWh
[codecarbon INFO @ 14:00:18] 0.000468 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:00:19] Energy consumed for RAM : 0.000038 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:00:19] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:00:19] Energy consumed for All CPU : 0.000466 kWh
[codecarbon INFO @ 14:00:19] 0.000504 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:00:20] Energy consumed for RAM : 0.000040 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:00:20] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:00:20] Energy consumed for All CPU : 0.000500 kWh
[codecarbon INFO @ 14:00:20] 0.000540 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:00:26] Energy consumed for RAM : 0.000044 kWh. RAM Power : 10.0 W
[codecarbon WARNING @ 14:00:29] Background scheduler didn't run for a long period (8s), results might be inaccurate
[codecarbon INFO @ 14:00:30] Energy consumed for RAM : 0.000070 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:00:30] Delta energy consumed for CPU with constant : 0.000303 kWh, power : 120.0 W
[codecarbon WARNING @ 14:00:29] Background scheduler didn't run for a long period (8s), results might be inaccurate
[codecarbon INFO @ 14:00:30] Energy consumed for RAM : 0.000095 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:00:30] Energy consumed for All CPU : 0.001091 kWh
[codecarbon INFO @ 14:00:29] Delta energy consumed for CPU with constant : 0.000288 kWh, power : 120.0 W
[codecarbon INFO @ 14:00:30] Energy consumed for All CPU : 0.001395 kWh
[codecarbon INFO @ 14:00:30] 0.001490 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:00:30] Delta energy consumed for CPU with constant : 0.000304 kWh, power : 120.0 W
[codecarbon INFO @ 14:00:30] 0.001490 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:00:30] Energy consumed for All CPU : 0.001395 kWh
[codecarbon INFO @ 14:00:30] 0.033708 g.CO2eq/s mean an estimation of 1,063.0243394063282 kg.CO2eq/year
[codecarbon INFO @ 14:00:30] 0.001490 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:00:30] 0.000000 g.CO2eq/s mean an estimation of 0.0 kg.CO2eq/year
[codecarbon INFO @ 14:00:30] Energy consumed for RAM : 0.000096 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:00:30] Delta energy consumed for CPU with constant : 0.000012 kWh, power : 120.0 W
[codecarbon INFO @ 14:00:30] Energy consumed for All CPU : 0.001407 kWh
[codecarbon INFO @ 14:00:30] 0.001503 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:00:31] Energy consumed for RAM : 0.000099 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:00:31] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 14:00:31] Energy consumed for All CPU : 0.001441 kWh
[codecarbon INFO @ 14:00:31] 0.001539 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:00:31] Energy consumed for RAM : 0.000100 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:00:31] Delta energy consumed for CPU with constant : 0.000011 kWh, power : 120.0 W
[codecarbon INFO @ 14:00:31] Energy consumed for All CPU : 0.001451 kWh
[codecarbon INFO @ 14:00:31] 0.001551 kWh of electricity and 0.000000 L of water were used since the beginning.

=== CodeCarbon Tracking Summary ===
Project: demo_experiment
Output CSV: /gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emissions_parquet.csv

Average rating per author

In [ ]:

# Initialize the tracker with detailed logging
tracker = EmissionsTracker(
    project_name="demo_experiment",
    output_dir=log_dir,
    measure_power_secs=1,        # frequency of power measurement
    log_level="info",            # ensures detailed console + file logs
    save_to_file=True,           # ensure CSV file is written
)

# Start tracking
tracker.start()

# Simulate a computation workload
for _ in range(1000):
    a = np.random.rand(500, 500)
    b = np.random.rand(500, 500)
    np.dot(a, b)

authors_df = book_df.explode('authors')
avg_rating_per_author = authors_df.groupby('authors')['review/score'].mean().reset_index()
avg_rating_per_author.rename(columns={'review/score': 'avg_rating'}, inplace=True)


# Stop tracking
emissions = tracker.stop()

# Print summary
print("\n=== CodeCarbon Tracking Summary ===")
print(f"Project: {tracker._project_name}")
print(f"Output CSV: {os.path.join(log_dir, 'emissions_parquet.csv')}")

[codecarbon WARNING @ 13:56:55] Multiple instances of codecarbon are allowed to run at the same time.
[codecarbon INFO @ 13:56:55] [setup] RAM Tracking...
[codecarbon INFO @ 13:56:55] [setup] CPU Tracking...
[codecarbon WARNING @ 13:56:56] No CPU tracking mode found. Falling back on estimation based on TDP for CPU.
 Linux OS detected: Please ensure RAPL files exist at /sys/class/powercap/intel-rapl/subsystem to measure CPU

[codecarbon INFO @ 13:56:56] CPU Model on constant consumption mode: AMD EPYC 7B12
[codecarbon WARNING @ 13:56:56] No CPU tracking mode found. Falling back on CPU constant mode.
[codecarbon INFO @ 13:56:56] [setup] GPU Tracking...
[codecarbon INFO @ 13:56:56] No GPU found.
[codecarbon INFO @ 13:56:56] The below tracking methods have been set up:
                RAM Tracking Method: RAM power estimation model
                CPU Tracking Method: global constant
                GPU Tracking Method: Unspecified

[codecarbon INFO @ 13:56:56] >>> Tracker's metadata:
[codecarbon INFO @ 13:56:56]   Platform system: Linux-6.6.105+-x86_64-with-glibc2.35
[codecarbon INFO @ 13:56:56]   Python version: 3.12.12
[codecarbon INFO @ 13:56:56]   CodeCarbon version: 3.0.8
[codecarbon INFO @ 13:56:56]   Available RAM : 12.671 GB
[codecarbon INFO @ 13:56:56]   CPU count: 2 thread(s) in 1 physical CPU(s)
[codecarbon INFO @ 13:56:56]   CPU model: AMD EPYC 7B12
[codecarbon INFO @ 13:56:56]   GPU count: None
[codecarbon INFO @ 13:56:56]   GPU model: None
[codecarbon INFO @ 13:56:57] Emissions data (if any) will be saved to file /gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emissions.csv
[codecarbon INFO @ 13:56:58] Energy consumed for RAM : 0.000003 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:56:58] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 13:56:58] Energy consumed for All CPU : 0.000034 kWh
[codecarbon INFO @ 13:56:58] 0.000036 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:56:59] Energy consumed for RAM : 0.000006 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:56:59] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:56:59] Energy consumed for All CPU : 0.000067 kWh
[codecarbon INFO @ 13:56:59] 0.000072 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:00] Energy consumed for RAM : 0.000008 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:00] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:00] Energy consumed for All CPU : 0.000100 kWh
[codecarbon INFO @ 13:57:00] 0.000108 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:01] Energy consumed for RAM : 0.000011 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:01] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:01] Energy consumed for All CPU : 0.000133 kWh
[codecarbon INFO @ 13:57:01] 0.000144 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:02] Energy consumed for RAM : 0.000014 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:02] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:02] Energy consumed for All CPU : 0.000166 kWh
[codecarbon INFO @ 13:57:02] 0.000180 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:03] Energy consumed for RAM : 0.000017 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:03] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:03] Energy consumed for All CPU : 0.000199 kWh
[codecarbon INFO @ 13:57:03] 0.000215 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:04] Energy consumed for RAM : 0.000019 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:04] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:04] Energy consumed for All CPU : 0.000232 kWh
[codecarbon INFO @ 13:57:04] 0.000252 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:05] Energy consumed for RAM : 0.000022 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:05] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:05] Energy consumed for All CPU : 0.000265 kWh
[codecarbon INFO @ 13:57:05] 0.000287 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:05] 0.016215 g.CO2eq/s mean an estimation of 511.3416334692422 kg.CO2eq/year
[codecarbon INFO @ 13:57:06] Energy consumed for RAM : 0.000025 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:06] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:06] Energy consumed for All CPU : 0.000299 kWh
[codecarbon INFO @ 13:57:06] 0.000323 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:07] Energy consumed for RAM : 0.000028 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:07] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:07] Energy consumed for All CPU : 0.000332 kWh
[codecarbon INFO @ 13:57:07] 0.000360 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:08] Energy consumed for RAM : 0.000030 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:08] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:08] Energy consumed for All CPU : 0.000365 kWh
[codecarbon INFO @ 13:57:08] 0.000395 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:09] Energy consumed for RAM : 0.000033 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:09] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:09] Energy consumed for All CPU : 0.000398 kWh
[codecarbon INFO @ 13:57:09] 0.000431 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:10] Energy consumed for RAM : 0.000036 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:10] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:10] Energy consumed for All CPU : 0.000432 kWh
[codecarbon INFO @ 13:57:10] 0.000468 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:11] Energy consumed for RAM : 0.000041 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:12] Delta energy consumed for CPU with constant : 0.000064 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:12] Energy consumed for All CPU : 0.000496 kWh
[codecarbon INFO @ 13:57:12] 0.000537 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:13] Energy consumed for RAM : 0.000044 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:13] Delta energy consumed for CPU with constant : 0.000029 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:13] Energy consumed for All CPU : 0.000525 kWh
[codecarbon INFO @ 13:57:13] 0.000569 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:14] Energy consumed for RAM : 0.000047 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:14] Delta energy consumed for CPU with constant : 0.000041 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:14] Energy consumed for All CPU : 0.000566 kWh
[codecarbon INFO @ 13:57:14] 0.000613 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:14] 0.015779 g.CO2eq/s mean an estimation of 497.59354834197757 kg.CO2eq/year
[codecarbon INFO @ 13:57:15] Energy consumed for RAM : 0.000050 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:15] Delta energy consumed for CPU with constant : 0.000031 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:15] Energy consumed for All CPU : 0.000597 kWh
[codecarbon INFO @ 13:57:15] 0.000647 kWh of electricity and 0.000000 L of water were used since the beginning.

=== CodeCarbon Tracking Summary ===
Project: demo_experiment
Output CSV: /gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emissions_parquet.csv

Number of reviews per publisher

In [ ]:

# Initialize the tracker with detailed logging
tracker = EmissionsTracker(
    project_name="demo_experiment",
    output_dir=log_dir,
    measure_power_secs=1,        # frequency of power measurement
    log_level="info",            # ensures detailed console + file logs
    save_to_file=True,           # ensure CSV file is written
)

# Start tracking
tracker.start()

# Simulate a computation workload
for _ in range(1000):
    a = np.random.rand(500, 500)
    b = np.random.rand(500, 500)
    np.dot(a, b)

reviews_per_publisher = book_df.groupby('publisher')['review/text'].count().reset_index()
reviews_per_publisher.rename(columns={'review/text': 'num_reviews'}, inplace=True)


# Stop tracking
emissions = tracker.stop()

# Print summary
print("\n=== CodeCarbon Tracking Summary ===")
print(f"Project: {tracker._project_name}")
print(f"Output CSV: {os.path.join(log_dir, 'emissions_parquet.csv')}")

[codecarbon WARNING @ 13:57:16] Multiple instances of codecarbon are allowed to run at the same time.
[codecarbon INFO @ 13:57:16] [setup] RAM Tracking...
[codecarbon INFO @ 13:57:16] [setup] CPU Tracking...
[codecarbon WARNING @ 13:57:17] No CPU tracking mode found. Falling back on estimation based on TDP for CPU.
 Linux OS detected: Please ensure RAPL files exist at /sys/class/powercap/intel-rapl/subsystem to measure CPU

[codecarbon INFO @ 13:57:17] CPU Model on constant consumption mode: AMD EPYC 7B12
[codecarbon WARNING @ 13:57:17] No CPU tracking mode found. Falling back on CPU constant mode.
[codecarbon INFO @ 13:57:17] [setup] GPU Tracking...
[codecarbon INFO @ 13:57:17] No GPU found.
[codecarbon INFO @ 13:57:17] The below tracking methods have been set up:
                RAM Tracking Method: RAM power estimation model
                CPU Tracking Method: global constant
                GPU Tracking Method: Unspecified

[codecarbon INFO @ 13:57:17] >>> Tracker's metadata:
[codecarbon INFO @ 13:57:17]   Platform system: Linux-6.6.105+-x86_64-with-glibc2.35
[codecarbon INFO @ 13:57:17]   Python version: 3.12.12
[codecarbon INFO @ 13:57:17]   CodeCarbon version: 3.0.8
[codecarbon INFO @ 13:57:17]   Available RAM : 12.671 GB
[codecarbon INFO @ 13:57:17]   CPU count: 2 thread(s) in 1 physical CPU(s)
[codecarbon INFO @ 13:57:17]   CPU model: AMD EPYC 7B12
[codecarbon INFO @ 13:57:17]   GPU count: None
[codecarbon INFO @ 13:57:17]   GPU model: None
[codecarbon INFO @ 13:57:17] Emissions data (if any) will be saved to file /gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emissions.csv
[codecarbon INFO @ 13:57:18] Energy consumed for RAM : 0.000003 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:18] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:18] Energy consumed for All CPU : 0.000034 kWh
[codecarbon INFO @ 13:57:18] 0.000036 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:19] Energy consumed for RAM : 0.000006 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:19] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:19] Energy consumed for All CPU : 0.000067 kWh
[codecarbon INFO @ 13:57:19] 0.000072 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:20] Energy consumed for RAM : 0.000008 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:20] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:20] Energy consumed for All CPU : 0.000100 kWh
[codecarbon INFO @ 13:57:20] 0.000108 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:21] Energy consumed for RAM : 0.000011 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:21] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:21] Energy consumed for All CPU : 0.000133 kWh
[codecarbon INFO @ 13:57:21] 0.000144 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:22] Energy consumed for RAM : 0.000014 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:22] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:22] Energy consumed for All CPU : 0.000167 kWh
[codecarbon INFO @ 13:57:22] 0.000180 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:23] Energy consumed for RAM : 0.000017 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:23] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:23] Energy consumed for All CPU : 0.000200 kWh
[codecarbon INFO @ 13:57:23] 0.000216 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:24] Energy consumed for RAM : 0.000019 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:24] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:24] Energy consumed for All CPU : 0.000233 kWh
[codecarbon INFO @ 13:57:24] 0.000252 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:25] Energy consumed for RAM : 0.000022 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:25] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:25] Energy consumed for All CPU : 0.000266 kWh
[codecarbon INFO @ 13:57:25] 0.000288 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:25] 0.016225 g.CO2eq/s mean an estimation of 511.6792692108034 kg.CO2eq/year
[codecarbon INFO @ 13:57:26] Energy consumed for RAM : 0.000025 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:26] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:27] Energy consumed for All CPU : 0.000299 kWh
[codecarbon INFO @ 13:57:27] 0.000324 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:27] Energy consumed for RAM : 0.000028 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:27] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:28] Energy consumed for All CPU : 0.000332 kWh
[codecarbon INFO @ 13:57:28] 0.000360 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:29] Energy consumed for RAM : 0.000030 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:29] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:29] Energy consumed for All CPU : 0.000365 kWh
[codecarbon INFO @ 13:57:29] 0.000396 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:30] Energy consumed for RAM : 0.000033 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:30] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:30] Energy consumed for All CPU : 0.000398 kWh
[codecarbon INFO @ 13:57:30] 0.000431 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:31] Energy consumed for RAM : 0.000036 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:31] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:31] Energy consumed for All CPU : 0.000431 kWh
[codecarbon INFO @ 13:57:31] 0.000467 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:32] Energy consumed for RAM : 0.000039 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:32] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:32] Energy consumed for All CPU : 0.000465 kWh
[codecarbon INFO @ 13:57:32] 0.000503 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:32] Energy consumed for RAM : 0.000041 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:32] Delta energy consumed for CPU with constant : 0.000030 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:32] Energy consumed for All CPU : 0.000494 kWh
[codecarbon INFO @ 13:57:32] 0.000535 kWh of electricity and 0.000000 L of water were used since the beginning.

=== CodeCarbon Tracking Summary ===
Project: demo_experiment
Output CSV: /gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emissions_parquet.csv

 Top 10 most-reviewed categories

In [ ]:

# Initialize the tracker with detailed logging
tracker = EmissionsTracker(
    project_name="demo_experiment",
    output_dir=log_dir,
    measure_power_secs=1,        # frequency of power measurement
    log_level="info",            # ensures detailed console + file logs
    save_to_file=True,           # ensure CSV file is written
)

# Start tracking
tracker.start()

# Simulate a computation workload
for _ in range(1000):
    a = np.random.rand(500, 500)
    b = np.random.rand(500, 500)
    np.dot(a, b)

categories_df = book_df.explode('categories')
top10_categories = categories_df.groupby('categories')['review/text'].count().reset_index()
top10_categories.rename(columns={'review/text': 'num_reviews'}, inplace=True)
top10_categories = top10_categories.sort_values(by='num_reviews', ascending=False).head(10)


# Stop tracking
emissions = tracker.stop()

# Print summary
print("\n=== CodeCarbon Tracking Summary ===")
print(f"Project: {tracker._project_name}")
print(f"Output CSV: {os.path.join(log_dir, 'emissions_parquet.csv')}")

[codecarbon WARNING @ 13:57:37] Multiple instances of codecarbon are allowed to run at the same time.
[codecarbon INFO @ 13:57:37] [setup] RAM Tracking...
[codecarbon INFO @ 13:57:37] [setup] CPU Tracking...
[codecarbon WARNING @ 13:57:38] No CPU tracking mode found. Falling back on estimation based on TDP for CPU.
 Linux OS detected: Please ensure RAPL files exist at /sys/class/powercap/intel-rapl/subsystem to measure CPU

[codecarbon INFO @ 13:57:38] CPU Model on constant consumption mode: AMD EPYC 7B12
[codecarbon WARNING @ 13:57:38] No CPU tracking mode found. Falling back on CPU constant mode.
[codecarbon INFO @ 13:57:38] [setup] GPU Tracking...
[codecarbon INFO @ 13:57:38] No GPU found.
[codecarbon INFO @ 13:57:38] The below tracking methods have been set up:
                RAM Tracking Method: RAM power estimation model
                CPU Tracking Method: global constant
                GPU Tracking Method: Unspecified

[codecarbon INFO @ 13:57:38] >>> Tracker's metadata:
[codecarbon INFO @ 13:57:38]   Platform system: Linux-6.6.105+-x86_64-with-glibc2.35
[codecarbon INFO @ 13:57:38]   Python version: 3.12.12
[codecarbon INFO @ 13:57:38]   CodeCarbon version: 3.0.8
[codecarbon INFO @ 13:57:38]   Available RAM : 12.671 GB
[codecarbon INFO @ 13:57:38]   CPU count: 2 thread(s) in 1 physical CPU(s)
[codecarbon INFO @ 13:57:38]   CPU model: AMD EPYC 7B12
[codecarbon INFO @ 13:57:38]   GPU count: None
[codecarbon INFO @ 13:57:38]   GPU model: None
[codecarbon INFO @ 13:57:38] Emissions data (if any) will be saved to file /gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emissions.csv
[codecarbon INFO @ 13:57:39] Energy consumed for RAM : 0.000003 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:39] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:39] Energy consumed for All CPU : 0.000034 kWh
[codecarbon INFO @ 13:57:39] 0.000036 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:40] Energy consumed for RAM : 0.000006 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:40] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:40] Energy consumed for All CPU : 0.000067 kWh
[codecarbon INFO @ 13:57:40] 0.000072 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:41] Energy consumed for RAM : 0.000008 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:41] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:41] Energy consumed for All CPU : 0.000100 kWh
[codecarbon INFO @ 13:57:41] 0.000108 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:42] Energy consumed for RAM : 0.000011 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:42] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:42] Energy consumed for All CPU : 0.000133 kWh
[codecarbon INFO @ 13:57:42] 0.000144 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:43] Energy consumed for RAM : 0.000014 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:43] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:43] Energy consumed for All CPU : 0.000166 kWh
[codecarbon INFO @ 13:57:43] 0.000180 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:44] Energy consumed for RAM : 0.000016 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:44] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:44] Energy consumed for All CPU : 0.000199 kWh
[codecarbon INFO @ 13:57:44] 0.000215 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:45] Energy consumed for RAM : 0.000019 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:45] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:45] Energy consumed for All CPU : 0.000232 kWh
[codecarbon INFO @ 13:57:45] 0.000251 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:46] Energy consumed for RAM : 0.000022 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:46] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:46] Energy consumed for All CPU : 0.000265 kWh
[codecarbon INFO @ 13:57:46] 0.000287 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:46] 0.016209 g.CO2eq/s mean an estimation of 511.1513752282505 kg.CO2eq/year
[codecarbon INFO @ 13:57:47] Energy consumed for RAM : 0.000025 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:47] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:47] Energy consumed for All CPU : 0.000299 kWh
[codecarbon INFO @ 13:57:47] 0.000323 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:48] Energy consumed for RAM : 0.000028 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:48] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:48] Energy consumed for All CPU : 0.000332 kWh
[codecarbon INFO @ 13:57:48] 0.000359 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:49] Energy consumed for RAM : 0.000030 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:49] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:49] Energy consumed for All CPU : 0.000365 kWh
[codecarbon INFO @ 13:57:49] 0.000395 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:50] Energy consumed for RAM : 0.000033 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:50] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:50] Energy consumed for All CPU : 0.000398 kWh
[codecarbon INFO @ 13:57:50] 0.000431 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:51] Energy consumed for RAM : 0.000036 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:51] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:51] Energy consumed for All CPU : 0.000431 kWh
[codecarbon INFO @ 13:57:51] 0.000467 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:52] Energy consumed for RAM : 0.000039 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:52] Delta energy consumed for CPU with constant : 0.000035 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:52] Energy consumed for All CPU : 0.000466 kWh
[codecarbon INFO @ 13:57:52] 0.000505 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:54] Energy consumed for RAM : 0.000043 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:54] Delta energy consumed for CPU with constant : 0.000049 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:54] Energy consumed for All CPU : 0.000515 kWh
[codecarbon INFO @ 13:57:54] 0.000558 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:55] Energy consumed for RAM : 0.000046 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:55] Delta energy consumed for CPU with constant : 0.000038 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:55] Energy consumed for All CPU : 0.000554 kWh
[codecarbon INFO @ 13:57:55] 0.000600 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:55] 0.016004 g.CO2eq/s mean an estimation of 504.69484581412775 kg.CO2eq/year
[codecarbon INFO @ 13:57:56] Energy consumed for RAM : 0.000049 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:56] Delta energy consumed for CPU with constant : 0.000041 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:56] Energy consumed for All CPU : 0.000595 kWh
[codecarbon INFO @ 13:57:56] 0.000644 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:58] Energy consumed for RAM : 0.000053 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:58] Delta energy consumed for CPU with constant : 0.000046 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:58] Energy consumed for All CPU : 0.000641 kWh
[codecarbon INFO @ 13:57:58] 0.000695 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:57:58] Energy consumed for RAM : 0.000057 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:57:58] Delta energy consumed for CPU with constant : 0.000000 kWh, power : 120.0 W
[codecarbon INFO @ 13:57:58] Energy consumed for All CPU : 0.000641 kWh
[codecarbon INFO @ 13:57:58] 0.000698 kWh of electricity and 0.000000 L of water were used since the beginning.

=== CodeCarbon Tracking Summary ===
Project: demo_experiment
Output CSV: /gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emissions_parquet.csv

Average review length

In [ ]:

# Initialize the tracker with detailed logging
tracker = EmissionsTracker(
    project_name="demo_experiment",
    output_dir=log_dir,
    measure_power_secs=1,        # frequency of power measurement
    log_level="info",            # ensures detailed console + file logs
    save_to_file=True,           # ensure CSV file is written
)

# Start tracking
tracker.start()

# Simulate a computation workload
for _ in range(1000):
    a = np.random.rand(500, 500)
    b = np.random.rand(500, 500)
    np.dot(a, b)

book_df['review_length'] = book_df['review/text'].apply(lambda x: len(str(x).split()))
avg_review_length = book_df['review_length'].mean()


# Stop tracking
emissions = tracker.stop()

# Print summary
print("\n=== CodeCarbon Tracking Summary ===")
print(f"Project: {tracker._project_name}")
print(f"Output CSV: {os.path.join(log_dir, 'emissions_parquet.csv')}")

[codecarbon WARNING @ 13:57:59] Multiple instances of codecarbon are allowed to run at the same time.
[codecarbon INFO @ 13:57:59] [setup] RAM Tracking...
[codecarbon INFO @ 13:57:59] [setup] CPU Tracking...
[codecarbon WARNING @ 13:58:01] No CPU tracking mode found. Falling back on estimation based on TDP for CPU.
 Linux OS detected: Please ensure RAPL files exist at /sys/class/powercap/intel-rapl/subsystem to measure CPU

[codecarbon INFO @ 13:58:01] CPU Model on constant consumption mode: AMD EPYC 7B12
[codecarbon WARNING @ 13:58:01] No CPU tracking mode found. Falling back on CPU constant mode.
[codecarbon INFO @ 13:58:01] [setup] GPU Tracking...
[codecarbon INFO @ 13:58:01] No GPU found.
[codecarbon INFO @ 13:58:01] The below tracking methods have been set up:
                RAM Tracking Method: RAM power estimation model
                CPU Tracking Method: global constant
                GPU Tracking Method: Unspecified

[codecarbon INFO @ 13:58:01] >>> Tracker's metadata:
[codecarbon INFO @ 13:58:01]   Platform system: Linux-6.6.105+-x86_64-with-glibc2.35
[codecarbon INFO @ 13:58:01]   Python version: 3.12.12
[codecarbon INFO @ 13:58:01]   CodeCarbon version: 3.0.8
[codecarbon INFO @ 13:58:01]   Available RAM : 12.671 GB
[codecarbon INFO @ 13:58:01]   CPU count: 2 thread(s) in 1 physical CPU(s)
[codecarbon INFO @ 13:58:01]   CPU model: AMD EPYC 7B12
[codecarbon INFO @ 13:58:01]   GPU count: None
[codecarbon INFO @ 13:58:01]   GPU model: None
[codecarbon INFO @ 13:58:01] Emissions data (if any) will be saved to file /gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emissions.csv
[codecarbon INFO @ 13:58:02] Energy consumed for RAM : 0.000003 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:02] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:02] Energy consumed for All CPU : 0.000034 kWh
[codecarbon INFO @ 13:58:02] 0.000036 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:03] Energy consumed for RAM : 0.000006 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:03] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:03] Energy consumed for All CPU : 0.000067 kWh
[codecarbon INFO @ 13:58:03] 0.000072 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:04] Energy consumed for RAM : 0.000008 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:04] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:04] Energy consumed for All CPU : 0.000100 kWh
[codecarbon INFO @ 13:58:04] 0.000108 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:05] Energy consumed for RAM : 0.000011 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:05] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:05] Energy consumed for All CPU : 0.000133 kWh
[codecarbon INFO @ 13:58:05] 0.000144 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:06] Energy consumed for RAM : 0.000014 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:06] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:06] Energy consumed for All CPU : 0.000166 kWh
[codecarbon INFO @ 13:58:06] 0.000180 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:07] Energy consumed for RAM : 0.000017 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:07] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:07] Energy consumed for All CPU : 0.000199 kWh
[codecarbon INFO @ 13:58:07] 0.000216 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:08] Energy consumed for RAM : 0.000019 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:08] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:08] Energy consumed for All CPU : 0.000233 kWh
[codecarbon INFO @ 13:58:08] 0.000252 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:09] Energy consumed for RAM : 0.000022 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:09] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:09] Energy consumed for All CPU : 0.000266 kWh
[codecarbon INFO @ 13:58:09] 0.000288 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:09] 0.016236 g.CO2eq/s mean an estimation of 512.0211815614692 kg.CO2eq/year
[codecarbon INFO @ 13:58:10] Energy consumed for RAM : 0.000025 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:10] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:10] Energy consumed for All CPU : 0.000299 kWh
[codecarbon INFO @ 13:58:10] 0.000324 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:11] Energy consumed for RAM : 0.000028 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:11] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:11] Energy consumed for All CPU : 0.000332 kWh
[codecarbon INFO @ 13:58:11] 0.000360 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:12] Energy consumed for RAM : 0.000030 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:12] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:12] Energy consumed for All CPU : 0.000365 kWh
[codecarbon INFO @ 13:58:12] 0.000395 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:13] Energy consumed for RAM : 0.000033 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:13] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:13] Energy consumed for All CPU : 0.000398 kWh
[codecarbon INFO @ 13:58:13] 0.000431 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:14] Energy consumed for RAM : 0.000036 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:14] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:14] Energy consumed for All CPU : 0.000431 kWh
[codecarbon INFO @ 13:58:14] 0.000467 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:15] Energy consumed for RAM : 0.000039 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:15] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:15] Energy consumed for All CPU : 0.000465 kWh
[codecarbon INFO @ 13:58:15] 0.000504 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:16] Energy consumed for RAM : 0.000041 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:16] Delta energy consumed for CPU with constant : 0.000032 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:16] Energy consumed for All CPU : 0.000497 kWh
[codecarbon INFO @ 13:58:16] 0.000538 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:17] Energy consumed for RAM : 0.000044 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:17] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:17] Energy consumed for All CPU : 0.000531 kWh
[codecarbon INFO @ 13:58:17] 0.000575 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:17] 0.015986 g.CO2eq/s mean an estimation of 504.14265744725645 kg.CO2eq/year
[codecarbon INFO @ 13:58:18] Energy consumed for RAM : 0.000047 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:18] Delta energy consumed for CPU with constant : 0.000032 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:18] Energy consumed for All CPU : 0.000563 kWh
[codecarbon INFO @ 13:58:18] 0.000610 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:19] Energy consumed for RAM : 0.000049 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:19] Delta energy consumed for CPU with constant : 0.000031 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:19] Energy consumed for All CPU : 0.000594 kWh
[codecarbon INFO @ 13:58:19] 0.000643 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:20] Energy consumed for RAM : 0.000052 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:20] Delta energy consumed for CPU with constant : 0.000031 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:20] Energy consumed for All CPU : 0.000626 kWh
[codecarbon INFO @ 13:58:20] 0.000677 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:21] Energy consumed for RAM : 0.000054 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:21] Delta energy consumed for CPU with constant : 0.000032 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:21] Energy consumed for All CPU : 0.000658 kWh
[codecarbon INFO @ 13:58:21] 0.000712 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:22] Energy consumed for RAM : 0.000057 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:22] Delta energy consumed for CPU with constant : 0.000032 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:22] Energy consumed for All CPU : 0.000690 kWh
[codecarbon INFO @ 13:58:22] 0.000746 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:23] Energy consumed for RAM : 0.000059 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:23] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:23] Energy consumed for All CPU : 0.000723 kWh
[codecarbon INFO @ 13:58:23] 0.000782 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:24] Energy consumed for RAM : 0.000062 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:24] Delta energy consumed for CPU with constant : 0.000030 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:24] Energy consumed for All CPU : 0.000753 kWh
[codecarbon INFO @ 13:58:24] 0.000815 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:25] Energy consumed for RAM : 0.000064 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:25] Delta energy consumed for CPU with constant : 0.000032 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:25] Energy consumed for All CPU : 0.000784 kWh
[codecarbon INFO @ 13:58:25] 0.000849 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:25] 0.015359 g.CO2eq/s mean an estimation of 484.35843958488016 kg.CO2eq/year
[codecarbon INFO @ 13:58:26] Energy consumed for RAM : 0.000067 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:26] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:26] Energy consumed for All CPU : 0.000817 kWh
[codecarbon INFO @ 13:58:26] 0.000884 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:27] Energy consumed for RAM : 0.000069 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:27] Delta energy consumed for CPU with constant : 0.000031 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:27] Energy consumed for All CPU : 0.000848 kWh
[codecarbon INFO @ 13:58:27] 0.000917 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:28] Energy consumed for RAM : 0.000072 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:28] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:28] Energy consumed for All CPU : 0.000881 kWh
[codecarbon INFO @ 13:58:28] 0.000953 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:29] Energy consumed for RAM : 0.000075 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:29] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:29] Energy consumed for All CPU : 0.000914 kWh
[codecarbon INFO @ 13:58:29] 0.000989 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:30] Energy consumed for RAM : 0.000077 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:30] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:30] Energy consumed for All CPU : 0.000947 kWh
[codecarbon INFO @ 13:58:30] 0.001024 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:31] Energy consumed for RAM : 0.000080 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:31] Delta energy consumed for CPU with constant : 0.000030 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:31] Energy consumed for All CPU : 0.000977 kWh
[codecarbon INFO @ 13:58:31] 0.001057 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:32] Energy consumed for RAM : 0.000083 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:32] Delta energy consumed for CPU with constant : 0.000032 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:32] Energy consumed for All CPU : 0.001009 kWh
[codecarbon INFO @ 13:58:32] 0.001092 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:33] Energy consumed for RAM : 0.000086 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:33] Delta energy consumed for CPU with constant : 0.000035 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:33] Energy consumed for All CPU : 0.001044 kWh
[codecarbon INFO @ 13:58:33] 0.001130 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:33] 0.015750 g.CO2eq/s mean an estimation of 496.69530725778685 kg.CO2eq/year
[codecarbon INFO @ 13:58:33] Energy consumed for RAM : 0.000086 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:33] Delta energy consumed for CPU with constant : 0.000000 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:33] Energy consumed for All CPU : 0.001044 kWh
[codecarbon INFO @ 13:58:33] 0.001130 kWh of electricity and 0.000000 L of water were used since the beginning.

=== CodeCarbon Tracking Summary ===
Project: demo_experiment
Output CSV: /gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emissions_parquet.csv

 most frequent keywords

In [ ]:

# Initialize the tracker with detailed logging
tracker = EmissionsTracker(
    project_name="demo_experiment",
    output_dir=log_dir,
    measure_power_secs=1,        # frequency of power measurement
    log_level="info",            # ensures detailed console + file logs
    save_to_file=True,           # ensure CSV file is written
)

# Start tracking
tracker.start()

# Simulate a computation workload
for _ in range(1000):
    a = np.random.rand(500, 500)
    b = np.random.rand(500, 500)
    np.dot(a, b)

all_words = ' '.join(book_df['review/text'].astype(str)).lower().split()
most_common_words = Counter(all_words).most_common(20)


# Stop tracking
emissions = tracker.stop()

# Print summary
print("\n=== CodeCarbon Tracking Summary ===")
print(f"Project: {tracker._project_name}")
print(f"Output CSV: {os.path.join(log_dir, 'emissions_parquet.csv')}")

[codecarbon WARNING @ 13:58:42] Multiple instances of codecarbon are allowed to run at the same time.
[codecarbon INFO @ 13:58:42] [setup] RAM Tracking...
[codecarbon INFO @ 13:58:42] [setup] CPU Tracking...
[codecarbon WARNING @ 13:58:43] No CPU tracking mode found. Falling back on estimation based on TDP for CPU.
 Linux OS detected: Please ensure RAPL files exist at /sys/class/powercap/intel-rapl/subsystem to measure CPU

[codecarbon INFO @ 13:58:43] CPU Model on constant consumption mode: AMD EPYC 7B12
[codecarbon WARNING @ 13:58:43] No CPU tracking mode found. Falling back on CPU constant mode.
[codecarbon INFO @ 13:58:43] [setup] GPU Tracking...
[codecarbon INFO @ 13:58:43] No GPU found.
[codecarbon INFO @ 13:58:43] The below tracking methods have been set up:
                RAM Tracking Method: RAM power estimation model
                CPU Tracking Method: global constant
                GPU Tracking Method: Unspecified

[codecarbon INFO @ 13:58:43] >>> Tracker's metadata:
[codecarbon INFO @ 13:58:43]   Platform system: Linux-6.6.105+-x86_64-with-glibc2.35
[codecarbon INFO @ 13:58:43]   Python version: 3.12.12
[codecarbon INFO @ 13:58:43]   CodeCarbon version: 3.0.8
[codecarbon INFO @ 13:58:43]   Available RAM : 12.671 GB
[codecarbon INFO @ 13:58:43]   CPU count: 2 thread(s) in 1 physical CPU(s)
[codecarbon INFO @ 13:58:43]   CPU model: AMD EPYC 7B12
[codecarbon INFO @ 13:58:43]   GPU count: None
[codecarbon INFO @ 13:58:43]   GPU model: None
[codecarbon INFO @ 13:58:44] Emissions data (if any) will be saved to file /gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emissions.csv
[codecarbon INFO @ 13:58:45] Energy consumed for RAM : 0.000003 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:45] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:45] Energy consumed for All CPU : 0.000034 kWh
[codecarbon INFO @ 13:58:45] 0.000036 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:46] Energy consumed for RAM : 0.000006 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:46] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:46] Energy consumed for All CPU : 0.000067 kWh
[codecarbon INFO @ 13:58:46] 0.000072 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:47] Energy consumed for RAM : 0.000008 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:47] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:47] Energy consumed for All CPU : 0.000100 kWh
[codecarbon INFO @ 13:58:47] 0.000108 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:48] Energy consumed for RAM : 0.000011 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:48] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:48] Energy consumed for All CPU : 0.000132 kWh
[codecarbon INFO @ 13:58:48] 0.000143 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:49] Energy consumed for RAM : 0.000014 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:49] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:49] Energy consumed for All CPU : 0.000165 kWh
[codecarbon INFO @ 13:58:49] 0.000179 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:50] Energy consumed for RAM : 0.000016 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:50] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:50] Energy consumed for All CPU : 0.000199 kWh
[codecarbon INFO @ 13:58:50] 0.000216 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:51] Energy consumed for RAM : 0.000019 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:51] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:51] Energy consumed for All CPU : 0.000232 kWh
[codecarbon INFO @ 13:58:51] 0.000251 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:52] Energy consumed for RAM : 0.000022 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:52] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:52] Energy consumed for All CPU : 0.000265 kWh
[codecarbon INFO @ 13:58:52] 0.000287 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:52] 0.016162 g.CO2eq/s mean an estimation of 509.68847270645097 kg.CO2eq/year
[codecarbon INFO @ 13:58:53] Energy consumed for RAM : 0.000025 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:53] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:53] Energy consumed for All CPU : 0.000298 kWh
[codecarbon INFO @ 13:58:53] 0.000323 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:54] Energy consumed for RAM : 0.000027 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:54] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:54] Energy consumed for All CPU : 0.000331 kWh
[codecarbon INFO @ 13:58:54] 0.000359 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:55] Energy consumed for RAM : 0.000030 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:55] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:55] Energy consumed for All CPU : 0.000364 kWh
[codecarbon INFO @ 13:58:55] 0.000395 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:56] Energy consumed for RAM : 0.000033 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:56] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:56] Energy consumed for All CPU : 0.000398 kWh
[codecarbon INFO @ 13:58:56] 0.000430 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 13:58:57] Energy consumed for RAM : 0.000036 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 13:58:57] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 13:58:57] Energy consumed for All CPU : 0.000431 kWh
[codecarbon INFO @ 13:58:57] 0.000466 kWh of electricity and 0.000000 L of water were used since the beginning.

Save to Parquet

In [ ]:

# Initialize the tracker with detailed logging
tracker = EmissionsTracker(
    project_name="demo_experiment",
    output_dir=log_dir,
    measure_power_secs=1,        # frequency of power measurement
    log_level="info",            # ensures detailed console + file logs
    save_to_file=True,           # ensure CSV file is written
)

# Start tracking
tracker.start()

# Simulate a computation workload
for _ in range(1000):
    a = np.random.rand(500, 500)
    b = np.random.rand(500, 500)
    np.dot(a, b)

book_df.to_parquet("book_df.parquet", compression="snappy", index=False)

# Stop tracking
emissions = tracker.stop()

# Print summary
print("\n=== CodeCarbon Tracking Summary ===")
print(f"Project: {tracker._project_name}")
print(f"Output CSV: {os.path.join(log_dir, 'emissions_parquet.csv')}")

[codecarbon WARNING @ 14:01:14] Multiple instances of codecarbon are allowed to run at the same time.
[codecarbon INFO @ 14:01:14] [setup] RAM Tracking...
[codecarbon INFO @ 14:01:14] [setup] CPU Tracking...
[codecarbon WARNING @ 14:01:15] No CPU tracking mode found. Falling back on estimation based on TDP for CPU.
 Linux OS detected: Please ensure RAPL files exist at /sys/class/powercap/intel-rapl/subsystem to measure CPU

[codecarbon INFO @ 14:01:15] CPU Model on constant consumption mode: AMD EPYC 7B12
[codecarbon WARNING @ 14:01:15] No CPU tracking mode found. Falling back on CPU constant mode.
[codecarbon INFO @ 14:01:15] [setup] GPU Tracking...
[codecarbon INFO @ 14:01:15] No GPU found.
[codecarbon INFO @ 14:01:15] The below tracking methods have been set up:
                RAM Tracking Method: RAM power estimation model
                CPU Tracking Method: global constant
                GPU Tracking Method: Unspecified

[codecarbon INFO @ 14:01:15] >>> Tracker's metadata:
[codecarbon INFO @ 14:01:15]   Platform system: Linux-6.6.105+-x86_64-with-glibc2.35
[codecarbon INFO @ 14:01:15]   Python version: 3.12.12
[codecarbon INFO @ 14:01:15]   CodeCarbon version: 3.0.8
[codecarbon INFO @ 14:01:15]   Available RAM : 12.671 GB
[codecarbon INFO @ 14:01:15]   CPU count: 2 thread(s) in 1 physical CPU(s)
[codecarbon INFO @ 14:01:15]   CPU model: AMD EPYC 7B12
[codecarbon INFO @ 14:01:15]   GPU count: None
[codecarbon INFO @ 14:01:15]   GPU model: None
[codecarbon INFO @ 14:01:15] Emissions data (if any) will be saved to file /gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emissions.csv
[codecarbon INFO @ 14:01:16] Energy consumed for RAM : 0.000003 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:16] Delta energy consumed for CPU with constant : 0.000034 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:16] Energy consumed for All CPU : 0.000034 kWh
[codecarbon INFO @ 14:01:16] 0.000036 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:17] Energy consumed for RAM : 0.000006 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:17] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:17] Energy consumed for All CPU : 0.000067 kWh
[codecarbon INFO @ 14:01:17] 0.000072 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:18] Energy consumed for RAM : 0.000008 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:18] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:18] Energy consumed for All CPU : 0.000100 kWh
[codecarbon INFO @ 14:01:18] 0.000108 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:19] Energy consumed for RAM : 0.000011 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:19] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:19] Energy consumed for All CPU : 0.000133 kWh
[codecarbon INFO @ 14:01:19] 0.000144 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:20] Energy consumed for RAM : 0.000014 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:20] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:20] Energy consumed for All CPU : 0.000166 kWh
[codecarbon INFO @ 14:01:20] 0.000180 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:21] Energy consumed for RAM : 0.000016 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:21] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:21] Energy consumed for All CPU : 0.000199 kWh
[codecarbon INFO @ 14:01:21] 0.000215 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:22] Energy consumed for RAM : 0.000019 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:22] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:22] Energy consumed for All CPU : 0.000232 kWh
[codecarbon INFO @ 14:01:22] 0.000251 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:23] Energy consumed for RAM : 0.000022 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:23] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:23] Energy consumed for All CPU : 0.000265 kWh
[codecarbon INFO @ 14:01:23] 0.000287 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:23] 0.016151 g.CO2eq/s mean an estimation of 509.3524711255074 kg.CO2eq/year
[codecarbon INFO @ 14:01:24] Energy consumed for RAM : 0.000025 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:24] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:24] Energy consumed for All CPU : 0.000298 kWh
[codecarbon INFO @ 14:01:24] 0.000323 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:25] Energy consumed for RAM : 0.000027 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:25] Delta energy consumed for CPU with constant : 0.000032 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:25] Energy consumed for All CPU : 0.000331 kWh
[codecarbon INFO @ 14:01:25] 0.000358 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:26] Energy consumed for RAM : 0.000030 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:26] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:26] Energy consumed for All CPU : 0.000364 kWh
[codecarbon INFO @ 14:01:26] 0.000394 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:27] Energy consumed for RAM : 0.000033 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:27] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:27] Energy consumed for All CPU : 0.000397 kWh
[codecarbon INFO @ 14:01:27] 0.000429 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:28] Energy consumed for RAM : 0.000036 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:28] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:28] Energy consumed for All CPU : 0.000430 kWh
[codecarbon INFO @ 14:01:28] 0.000465 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:29] Energy consumed for RAM : 0.000038 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:29] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:29] Energy consumed for All CPU : 0.000463 kWh
[codecarbon INFO @ 14:01:29] 0.000501 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon WARNING @ 14:01:34] Background scheduler didn't run for a long period (4s), results might be inaccurate
[codecarbon INFO @ 14:01:34] Energy consumed for RAM : 0.000052 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:35] Delta energy consumed for CPU with constant : 0.000204 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:40] Energy consumed for All CPU : 0.000667 kWh
[codecarbon INFO @ 14:01:40] 0.000718 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon WARNING @ 14:01:40] Background scheduler didn't run for a long period (10s), results might be inaccurate
[codecarbon WARNING @ 14:01:40] Background scheduler didn't run for a long period (10s), results might be inaccurate
[codecarbon INFO @ 14:01:40] Energy consumed for RAM : 0.000052 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:40] Energy consumed for RAM : 0.000052 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:40] Delta energy consumed for CPU with constant : 0.000001 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:40] Delta energy consumed for CPU with constant : 0.000000 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:40] Energy consumed for All CPU : 0.000668 kWh
[codecarbon INFO @ 14:01:40] 0.000719 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:40] Energy consumed for All CPU : 0.000668 kWh
[codecarbon INFO @ 14:01:40] 0.000719 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:40] 0.011786 g.CO2eq/s mean an estimation of 371.6778246017145 kg.CO2eq/year
[codecarbon INFO @ 14:01:40] 0.000000 g.CO2eq/s mean an estimation of 0 kg.CO2eq/year
[codecarbon INFO @ 14:01:41] Energy consumed for RAM : 0.000054 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:41] Delta energy consumed for CPU with constant : 0.000032 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:41] Energy consumed for All CPU : 0.000700 kWh
[codecarbon INFO @ 14:01:41] 0.000754 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:42] Energy consumed for RAM : 0.000057 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:42] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:42] Energy consumed for All CPU : 0.000733 kWh
[codecarbon INFO @ 14:01:42] 0.000790 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:43] Energy consumed for RAM : 0.000060 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:43] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:43] Energy consumed for All CPU : 0.000766 kWh
[codecarbon INFO @ 14:01:43] 0.000826 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:44] Energy consumed for RAM : 0.000063 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:44] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:44] Energy consumed for All CPU : 0.000799 kWh
[codecarbon INFO @ 14:01:44] 0.000862 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:45] Energy consumed for RAM : 0.000065 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:45] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:45] Energy consumed for All CPU : 0.000833 kWh
[codecarbon INFO @ 14:01:45] 0.000898 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:46] Energy consumed for RAM : 0.000068 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:46] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:46] Energy consumed for All CPU : 0.000866 kWh
[codecarbon INFO @ 14:01:46] 0.000934 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:47] Energy consumed for RAM : 0.000071 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:47] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:47] Energy consumed for All CPU : 0.000899 kWh
[codecarbon INFO @ 14:01:47] 0.000970 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:48] Energy consumed for RAM : 0.000074 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:48] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:48] Energy consumed for All CPU : 0.000932 kWh
[codecarbon INFO @ 14:01:48] 0.001006 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:48] 0.016277 g.CO2eq/s mean an estimation of 513.3129149308078 kg.CO2eq/year
[codecarbon INFO @ 14:01:49] Energy consumed for RAM : 0.000077 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:49] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:49] Energy consumed for All CPU : 0.000966 kWh
[codecarbon INFO @ 14:01:49] 0.001042 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:50] Energy consumed for RAM : 0.000079 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:50] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:50] Energy consumed for All CPU : 0.000999 kWh
[codecarbon INFO @ 14:01:50] 0.001078 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:51] Energy consumed for RAM : 0.000082 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:51] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:51] Energy consumed for All CPU : 0.001032 kWh
[codecarbon INFO @ 14:01:51] 0.001114 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:52] Energy consumed for RAM : 0.000085 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:52] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:52] Energy consumed for All CPU : 0.001065 kWh
[codecarbon INFO @ 14:01:52] 0.001150 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:53] Energy consumed for RAM : 0.000088 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:53] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:53] Energy consumed for All CPU : 0.001099 kWh
[codecarbon INFO @ 14:01:53] 0.001186 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:54] Energy consumed for RAM : 0.000090 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:54] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:54] Energy consumed for All CPU : 0.001132 kWh
[codecarbon INFO @ 14:01:54] 0.001222 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:55] Energy consumed for RAM : 0.000093 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:55] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:55] Energy consumed for All CPU : 0.001165 kWh
[codecarbon INFO @ 14:01:55] 0.001258 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:56] Energy consumed for RAM : 0.000096 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:56] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:56] Energy consumed for All CPU : 0.001198 kWh
[codecarbon INFO @ 14:01:56] 0.001294 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:56] 0.016265 g.CO2eq/s mean an estimation of 512.9422003628681 kg.CO2eq/year
[codecarbon INFO @ 14:01:57] Energy consumed for RAM : 0.000099 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:57] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:57] Energy consumed for All CPU : 0.001231 kWh
[codecarbon INFO @ 14:01:57] 0.001330 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:58] Energy consumed for RAM : 0.000101 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:58] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:58] Energy consumed for All CPU : 0.001264 kWh
[codecarbon INFO @ 14:01:58] 0.001366 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:01:59] Energy consumed for RAM : 0.000104 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:01:59] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:01:59] Energy consumed for All CPU : 0.001298 kWh
[codecarbon INFO @ 14:01:59] 0.001402 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:02:00] Energy consumed for RAM : 0.000107 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:02:00] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:02:00] Energy consumed for All CPU : 0.001331 kWh
[codecarbon INFO @ 14:02:00] 0.001438 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:02:01] Energy consumed for RAM : 0.000110 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:02:01] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:02:01] Energy consumed for All CPU : 0.001364 kWh
[codecarbon INFO @ 14:02:01] 0.001474 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:02:02] Energy consumed for RAM : 0.000112 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:02:02] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:02:02] Energy consumed for All CPU : 0.001398 kWh
[codecarbon INFO @ 14:02:02] 0.001510 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:02:03] Energy consumed for RAM : 0.000115 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:02:03] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:02:03] Energy consumed for All CPU : 0.001431 kWh
[codecarbon INFO @ 14:02:03] 0.001546 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:02:04] Energy consumed for RAM : 0.000118 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:02:04] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:02:04] Energy consumed for All CPU : 0.001464 kWh
[codecarbon INFO @ 14:02:04] 0.001582 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:02:04] 0.016286 g.CO2eq/s mean an estimation of 513.5853312424645 kg.CO2eq/year
[codecarbon INFO @ 14:02:05] Energy consumed for RAM : 0.000121 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:02:05] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:02:05] Energy consumed for All CPU : 0.001497 kWh
[codecarbon INFO @ 14:02:05] 0.001618 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:02:06] Energy consumed for RAM : 0.000124 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:02:06] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:02:06] Energy consumed for All CPU : 0.001530 kWh
[codecarbon INFO @ 14:02:06] 0.001654 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:02:07] Energy consumed for RAM : 0.000126 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:02:07] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:02:07] Energy consumed for All CPU : 0.001564 kWh
[codecarbon INFO @ 14:02:07] 0.001690 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:02:08] Energy consumed for RAM : 0.000129 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:02:08] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:02:08] Energy consumed for All CPU : 0.001597 kWh
[codecarbon INFO @ 14:02:08] 0.001726 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:02:09] Energy consumed for RAM : 0.000132 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 14:02:09] Delta energy consumed for CPU with constant : 0.000033 kWh, power : 120.0 W
[codecarbon INFO @ 14:02:09] Energy consumed for All CPU : 0.001630 kWh
[codecarbon INFO @ 14:02:09] 0.001762 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 14:02:10] Energy consumed for RAM : 0.000135 kWh. RAM Power : 10.0 W

=== CodeCarbon Tracking Summary ===
Project: demo_experiment
Output CSV: /gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emissions_parquet.csv

Visualisation des deux émisions

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/gdrive')

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).

In [ ]:
parquet_path = "/gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emission_parquet.csv"
emission_parquet = pd.read_csv(parquet_path,sep=';')

csv_path = "/gdrive/MyDrive/TP2_Green_IT/Data/carbon_logs_TP3/emission_csv.csv"
emission_csv = pd.read_csv(csv_path,sep=';')

emission_csv['Format'] = 'CSV'
emission_parquet['Format'] = 'Parquet'
emission_parquet.columns = emission_parquet.columns.str.strip()
emission_csv.columns = emission_csv.columns.str.strip()

In [ ]:
emission_csv['CO₂ (kg)'] = emission_csv['CO₂ (kg)'] * 1000   # g
emission_parquet['CO₂ (kg)'] = emission_parquet['CO₂ (kg)'] * 1000  # g

In [ ]:
emissions_df = pd.concat([emission_csv, emission_parquet], ignore_index=True)

In [ ]:
emissions_df['CO₂ (kg)'] = pd.to_numeric(emissions_df['CO₂ (kg)'], errors='coerce') * 1000

# 🔹 Agréger CO₂ total par format
co2_summary = emissions_df.groupby('Format')['CO₂ (kg)'].sum().reset_index()

# 🔹 Plot
plt.figure(figsize=(8,5))
sns.barplot(x='Format', y='CO₂ (kg)', data=co2_summary, palette='salmon')
plt.title("Émissions totales de CO₂ par format")
plt.ylabel("CO₂ émis (g)")
plt.xlabel("Format")
plt.tight_layout()
plt.show()

ValueError: Grouper for 'Format' not 1-dimensional